export const POPULAR_LOCATIONS: readonly string[] = [
  'Remote (Global)',
  'Remote (US)',
  'Remote (Canada)',
  'Remote (EU)',
  'Remote (UK)',
  'Remote (LATAM)',
  'Remote (APAC)',
  'Remote (EMEA)',
  'New York, USA',
  'San Francisco, USA',
  'Los Angeles, USA',
  'Austin, USA',
  'Boston, USA',
  'Seattle, USA',
  'Chicago, USA',
  'Denver, USA',
  'Miami, USA',
  'Washington DC, USA',
  'London, UK',
  'Berlin, Germany',
  'Paris, France',
  'Amsterdam, Netherlands',
  'Lisbon, Portugal',
  'Madrid, Spain',
  'Barcelona, Spain',
  'Zurich, Switzerland',
  'Zug, Switzerland',
  'Munich, Germany',
  'Dublin, Ireland',
  'Stockholm, Sweden',
  'Copenhagen, Denmark',
  'Warsaw, Poland',
  'Prague, Czechia',
  'Singapore',
  'Tokyo, Japan',
  'Hong Kong',
  'Seoul, South Korea',
  'Bangalore, India',
  'Mumbai, India',
  'Tel Aviv, Israel',
  'Dubai, UAE',
  'Abu Dhabi, UAE',
  'Bangkok, Thailand',
  'Hanoi, Vietnam',
  'Toronto, Canada',
  'Vancouver, Canada',
  'Mexico City, Mexico',
  'Buenos Aires, Argentina',
  'São Paulo, Brazil',
  'Bogotá, Colombia',
  'Santiago, Chile',
  'Sydney, Australia',
  'Melbourne, Australia',
  'Lagos, Nigeria',
  'Cape Town, South Africa',
  'Nairobi, Kenya',
];
