/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by: yarn generate:course-stats (scripts/academy/generate-course-stats.mts)
 *
 * Modules and lessons per course url for each landing track (index C8), from content/academy.
 */
import type { CourseStats } from './course-outline';

export type CourseStatsTrack = "avalanche-l1" | "blockchain" | "entrepreneur" | "team1";

export const COURSE_STATS: Record<CourseStatsTrack, Record<string, CourseStats>> = {
  "avalanche-l1": {
    "/academy/avalanche-l1/access-restriction": { modules: 6, lessons: 22 },
    "/academy/avalanche-l1/avalanche-fundamentals": { modules: 4, lessons: 31 },
    "/academy/avalanche-l1/customizing-evm": { modules: 9, lessons: 59 },
    "/academy/avalanche-l1/erc20-bridge": { modules: 4, lessons: 21 },
    "/academy/avalanche-l1/interchain-messaging": { modules: 6, lessons: 30 },
    "/academy/avalanche-l1/l1-native-tokenomics": { modules: 8, lessons: 36 },
    "/academy/avalanche-l1/native-token-bridge": { modules: 3, lessons: 22 },
    "/academy/avalanche-l1/permissioned-l1s": { modules: 7, lessons: 40 },
    "/academy/avalanche-l1/permissionless-l1s": { modules: 6, lessons: 30 },
  },
  "blockchain": {
    "/academy/blockchain/blockchain-fundamentals": { modules: 8, lessons: 24 },
    "/academy/blockchain/encrypted-erc": { modules: 5, lessons: 12 },
    "/academy/blockchain/nft-deployment": { modules: 5, lessons: 5 },
    "/academy/blockchain/solidity-foundry": { modules: 6, lessons: 30 },
    "/academy/blockchain/x402-payment-infrastructure": { modules: 4, lessons: 20 },
  },
  "entrepreneur": {
    "/academy/entrepreneur/foundations-web3-venture": { modules: 4, lessons: 34 },
    "/academy/entrepreneur/fundraising-finance": { modules: 3, lessons: 26 },
    "/academy/entrepreneur/go-to-market": { modules: 3, lessons: 30 },
    "/academy/entrepreneur/web3-community-architect": { modules: 2, lessons: 23 },
  },
  "team1": {
    "/academy/team1/team1-advanced-technical-member": { modules: 0, lessons: 4 },
    "/academy/team1/team1-event-organizer-pro": { modules: 0, lessons: 7 },
    "/academy/team1/team1-fundamentals": { modules: 0, lessons: 6 },
    "/academy/team1/team1-organizing-first-event": { modules: 0, lessons: 6 },
    "/academy/team1/team1-soft-skills": { modules: 0, lessons: 6 },
    "/academy/team1/team1-technical-member": { modules: 0, lessons: 7 },
  },
};
