/**
 * Writes lib/academy/course-stats.generated.ts: modules and lessons per course url for each
 * landing track (index C8), computed from content/academy. The landing pages read that module,
 * so they never import lib/source, which loads every MDX module of the site.
 *
 * Run: yarn generate:course-stats
 */
import fs from 'node:fs';
import { createRequire } from 'node:module';
import path from 'node:path';
import type { CourseStats } from '../../lib/academy/course-outline';
import { loadAcademyTree } from './content-tree.mts';

// tsx runs lib/ as CommonJS (package.json sets no "type"), and Node's ESM loader cannot see the
// named exports of a CommonJS module, so the outline module is loaded with require.
const requireCjs = createRequire(import.meta.url);
const { getCourseStats } = requireCjs('../../lib/academy/course-outline.ts') as typeof import('../../lib/academy/course-outline');

const OUTPUT_FILE = path.join(process.cwd(), 'lib/academy/course-stats.generated.ts');
// The landing tracks by url segment, which is also the course outline's track key (index C5).
const TRACKS = ['avalanche-l1', 'blockchain', 'entrepreneur', 'team1'] as const;

const HEADER = `/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by: yarn generate:course-stats (scripts/academy/generate-course-stats.mts)
 *
 * Modules and lessons per course url for each landing track (index C8), from content/academy.
 */`;

function trackBlock(track: string, stats: Record<string, CourseStats>): string {
  const lines = Object.keys(stats)
    .sort()
    .map((url) => `    ${JSON.stringify(url)}: { modules: ${stats[url].modules}, lessons: ${stats[url].lessons} },`);
  return [`  ${JSON.stringify(track)}: {`, ...lines, '  },'].join('\n');
}

const tree = loadAcademyTree();
const blocks = TRACKS.map((track) => trackBlock(track, getCourseStats(tree, track)));
const output = [
  HEADER,
  "import type { CourseStats } from './course-outline';",
  '',
  `export type CourseStatsTrack = ${TRACKS.map((track) => JSON.stringify(track)).join(' | ')};`,
  '',
  'export const COURSE_STATS: Record<CourseStatsTrack, Record<string, CourseStats>> = {',
  ...blocks,
  '};',
  '',
].join('\n');

fs.writeFileSync(OUTPUT_FILE, output);
process.stdout.write(`Wrote ${path.relative(process.cwd(), OUTPUT_FILE)} (${TRACKS.length} tracks)\n`);
