import l1ChainsData from "@/constants/l1-chains.json";
import type { Recipe } from "./cache";
import type { ChartSpec, Drill } from "./types";
import type { VisualSpec } from "./visual";

/* The suggested questions' answers, fixed: the SQL, chart, drill and
   layout the model wrote for each one (captured 2026-09-28), kept here so a
   click on a suggestion runs its SQL at once and asks no model, for the
   layout either. A question typed another way, or a follow-up, still goes
   to the model. Every mainnet L1 shares one set, filled in with its own
   chain id and token. */

interface Fixed {
  q: string;
  title: string;
  note: string;
  sql: string;
  chart: ChartSpec;
  drill: Drill | null;
  visual: VisualSpec | null;
}

/** the C-Chain's suggestions (EXAMPLES) */
const CCHAIN: Fixed[] = [
  {
    q: "Transactions per 5 minutes, with reverts",
    title: "Transactions per 5 minutes, with reverts",
    note: "Transactions charged per 5-minute period in the last 6 hours. The current 5-minute period is incomplete.",
    sql: "SELECT toStartOfFiveMinutes(block_time) AS t, count() AS txs, countIf(NOT success) AS reverted, round(100 * countIf(NOT success) / count(), 2) AS revert_pct FROM raw_txs WHERE chain_id = 43114 AND block_time >= toStartOfFiveMinutes(now()) - INTERVAL 6 HOUR GROUP BY t ORDER BY t\nLIMIT 2000",
    chart: { kind: "bar", x: "t", series: [{ column: "txs", label: "Transactions", unit: "txs" }, { column: "reverted", label: "Reverted", unit: "txs" }, { column: "revert_pct", label: "Revert rate", unit: "%" }] },
    drill: { sql: "SELECT block_time AS t, block_number, concat('0x', hex(hash)) AS tx_hash, lower(concat('0x', hex(`from`))) AS from_address, lower(concat('0x', hex(`to`))) AS to_address, concat('0x', hex(substring(input, 1, 4))) AS method_id, gas_used AS gas_charged, toFloat64(gas_used) * gas_price / 1e18 AS fee_avax, toUInt8(success) AS status FROM raw_txs WHERE chain_id = 43114 AND block_time >= toStartOfFiveMinutes(now()) - INTERVAL 6 HOUR AND toStartOfFiveMinutes(block_time) = {{t}} ORDER BY block_time DESC LIMIT 50", title: "Transactions in the 5 minutes from {{t}}" },
    visual: { stats: [{ label: "Transactions", column: "txs", agg: "sum", format: "compact" }, { label: "Reverted", column: "reverted", agg: "sum", format: "compact" }, { label: "Peak period", column: "txs", agg: "max", format: "number" }, { label: "Peak revert rate", column: "revert_pct", agg: "max", format: "percent" }], panels: [{ title: "Transactions and reverts", kind: "bar", x: "t", series: [{ column: "txs", label: "Transactions", format: "number", axis: "left", mark: "bar", transform: "none", dashed: false }, { column: "reverted", label: "Reverted", format: "number", axis: "left", mark: "bar", transform: "none", dashed: false }], markers: [], bands: [], stacked: false, sortDir: "desc", referenceLines: [], width: "full" }, { title: "Revert rate", kind: "line", x: "t", series: [{ column: "revert_pct", label: "Revert rate", format: "percent", axis: "left", mark: "auto", transform: "none", dashed: false }], markers: [], bands: [], stacked: false, sortDir: "desc", referenceLines: [], width: "full" }], callouts: [] },
  },
  {
    q: "Busiest senders in the last hour",
    title: "Busiest senders in the last hour",
    note: "The 15 senders with the most transactions in the last hour.",
    sql: "SELECT lower(concat('0x', hex(`from`))) AS sender, count() AS txs, countIf(NOT success) AS reverted, uniqExact(`to`) AS recipients, count() OVER () AS of_total FROM raw_txs WHERE chain_id = 43114 AND block_time >= now() - INTERVAL 1 HOUR GROUP BY `from` ORDER BY txs DESC LIMIT 15",
    chart: { kind: "bar", x: "sender", series: [{ column: "txs", label: "Transactions" }, { column: "reverted", label: "Reverted" }] },
    drill: { sql: "SELECT block_time AS t, block_number, concat('0x', hex(hash)) AS tx_hash, lower(concat('0x', hex(`from`))) AS from_address, lower(concat('0x', hex(`to`))) AS to_address, concat('0x', hex(substring(input, 1, 4))) AS method_id, gas_used AS gas_charged, toFloat64(gas_used) * gas_price / 1e18 AS fee_avax, toUInt8(success) AS status FROM raw_txs WHERE chain_id = 43114 AND block_time >= now() - INTERVAL 1 HOUR AND `from` = {{sender:bytes}} ORDER BY block_time DESC LIMIT 50", title: "Transactions from {{sender}} in the last hour" },
    visual: { stats: [{ label: "Transactions", column: "txs", agg: "sum", format: "compact" }, { label: "Senders", column: "sender", agg: "distinct", format: "number" }, { label: "Reverted", column: "reverted", agg: "sum", format: "compact" }, { label: "Top sender", column: "txs", agg: "max", format: "number" }], panels: [{ title: "Transactions per sender", kind: "hbar", x: "sender", series: [{ column: "txs", label: "Transactions", format: "number", axis: "left", mark: "auto", transform: "none", dashed: false }], markers: [], bands: [], stacked: false, sortBy: "txs", sortDir: "desc", topN: 15, referenceLines: [], width: "half" }, { title: "Reverted per sender", kind: "hbar", x: "sender", series: [{ column: "reverted", label: "Reverted", format: "number", axis: "left", mark: "auto", transform: "none", dashed: false }], markers: [], bands: [], stacked: false, sortBy: "txs", sortDir: "desc", topN: 15, referenceLines: [], width: "half" }], callouts: [] },
  },
  {
    q: "Fees burned per 5 minutes",
    title: "Fees burned per 5 minutes",
    note: "Every transaction burns its fee: gas used times gas price. The current 5-minute period is still in progress.",
    sql: "SELECT toStartOfFiveMinutes(block_time) AS t, sum(toFloat64(gas_used) * gas_price) / 1e18 AS fees_avax, max(toFloat64(gas_used) * gas_price) / 1e18 AS max_fee_avax, concat('0x', lower(hex(argMax(hash, toFloat64(gas_used) * gas_price)))) AS max_fee_tx, count() AS txs FROM raw_txs WHERE chain_id = 43114 AND block_time >= toStartOfFiveMinutes(now()) - INTERVAL 6 HOUR GROUP BY t ORDER BY t\nLIMIT 2000",
    chart: { kind: "line", x: "t", series: [{ column: "fees_avax", label: "Fees burned", unit: "AVAX" }] },
    drill: { sql: "SELECT block_time AS t, block_number, concat('0x', hex(hash)) AS tx_hash, lower(concat('0x', hex(`from`))) AS from_address, lower(concat('0x', hex(`to`))) AS to_address, concat('0x', hex(substring(input, 1, 4))) AS method_id, gas_used AS gas_charged, toFloat64(gas_used) * gas_price / 1e18 AS fee_avax, toUInt8(success) AS status FROM raw_txs WHERE chain_id = 43114 AND block_time >= toStartOfFiveMinutes(now()) - INTERVAL 6 HOUR AND toStartOfFiveMinutes(block_time) = {{t}} ORDER BY block_time DESC LIMIT 50", title: "Transactions in the 5 minutes from {{t}}" },
    visual: { stats: [{ label: "Fees burned", column: "fees_avax", agg: "sum", format: "avax" }, { label: "Peak 5 minutes", column: "fees_avax", agg: "max", format: "avax" }, { label: "Transactions", column: "txs", agg: "sum", format: "compact" }, { label: "Largest single fee", column: "max_fee_avax", agg: "max", format: "avax" }], panels: [{ title: "Fees burned", kind: "line", x: "t", series: [{ column: "fees_avax", label: "Fees burned", format: "avax", axis: "left", mark: "line", transform: "none", dashed: false }], markers: [], bands: [], stacked: false, sortDir: "desc", referenceLines: [], width: "full" }, { title: "Transactions and fees", kind: "bar", x: "t", series: [{ column: "txs", label: "Transactions", format: "number", axis: "left", mark: "bar", transform: "none", dashed: false }, { column: "max_fee_avax", label: "Largest fee", format: "avax", axis: "right", mark: "line", transform: "none", dashed: false }], markers: [], bands: [], stacked: false, sortDir: "desc", referenceLines: [], width: "full" }], callouts: [] },
  },
  {
    q: "Gas reserved per block against the limit",
    title: "Gas reserved per block versus the limit",
    note: "Each point is one block in the last 30 minutes, showing the gas reserved (the sum of its transactions gas limits) against the block gas limit.",
    sql: "SELECT block_number, block_time AS t, gas_used AS gas_reserved, gas_limit FROM raw_blocks WHERE chain_id = 43114 AND block_time >= now() - INTERVAL 30 MINUTE ORDER BY block_number\nLIMIT 2000",
    chart: { kind: "line", x: "t", series: [{ column: "gas_reserved", label: "Gas reserved", unit: "gas" }, { column: "gas_limit", label: "Gas limit", unit: "gas" }] },
    drill: null,
    visual: { stats: [{ label: "Blocks", column: "block_number", agg: "count", format: "number" }, { label: "Avg gas reserved", column: "gas_reserved", agg: "avg", format: "gas" }, { label: "Peak block", column: "gas_reserved", agg: "max", format: "gas" }, { label: "Block gas limit", column: "gas_limit", agg: "max", format: "gas" }], panels: [{ title: "Gas reserved per block", kind: "line", x: "t", series: [{ column: "gas_reserved", label: "Gas reserved", format: "gas", axis: "left", mark: "line", transform: "none", dashed: false }, { column: "gas_reserved", label: "Rolling average", format: "gas", axis: "left", mark: "auto", transform: "rolling", dashed: true }], markers: [], bands: [], stacked: false, sortDir: "desc", referenceLines: [{ y: 80000000, label: "Block gas limit 80M" }], width: "full" }], callouts: [] },
  },
  {
    q: "Most called methods",
    title: "Most called methods, last 24 hours",
    note: "Ranking of methods by call count. Reverted count, callers (senders of calls), and share of the total counted. The contract that holds most of each method's calls is named where it dominates. Contract names and method signatures are decoded by the server where known.",
    sql: "SELECT method_id, if(top_calls * 2 > txs, top_contract, NULL) AS contract, contracts, txs, reverted, callers, round(100 * txs / sum(txs) OVER (), 2) AS share_pct, count() OVER () AS of_total FROM (SELECT method_id, argMax(callee, n) AS top_contract, max(n) AS top_calls, uniqExact(callee) AS contracts, sum(n) AS txs, sum(r) AS reverted, uniqExactMerge(s) AS callers FROM (SELECT concat('0x', hex(substring(input, 1, 4))) AS method_id, lower(concat('0x', hex(`to`))) AS callee, count() AS n, countIf(NOT success) AS r, uniqExactState(`from`) AS s FROM raw_txs WHERE chain_id = 43114 AND block_time >= now() - INTERVAL 1 DAY AND length(input) >= 4 GROUP BY method_id, callee) GROUP BY method_id) ORDER BY txs DESC LIMIT 15",
    chart: { kind: "bar", x: "method_id", series: [{ column: "txs", label: "Calls", unit: "txs" }, { column: "reverted", label: "Reverted", unit: "txs" }, { column: "callers", label: "Senders", unit: "addresses" }, { column: "share_pct", label: "Share", unit: "%" }] },
    drill: { sql: "SELECT block_time AS t, block_number, concat('0x', hex(hash)) AS tx_hash, lower(concat('0x', hex(`from`))) AS from_address, lower(concat('0x', hex(`to`))) AS to_address, concat('0x', hex(substring(input, 1, 4))) AS method_id, gas_used AS gas_charged, toFloat64(gas_used) * gas_price / 1e18 AS fee_avax, toUInt8(success) AS status FROM raw_txs WHERE chain_id = 43114 AND block_time >= now() - INTERVAL 1 DAY AND substring(input, 1, 4) = {{method_id:bytes}} ORDER BY block_time DESC LIMIT 50", title: "Calls to {{method_id}}" },
    visual: { stats: [{ label: "Top method calls", column: "txs", agg: "max", format: "compact" }, { label: "Leader share", column: "share_pct", agg: "max", format: "percent" }, { label: "Most reverted", column: "reverted", agg: "max", format: "compact" }, { label: "Most callers", column: "callers", agg: "max", format: "compact" }], panels: [{ title: "Calls per method", kind: "hbar", x: "method_id", series: [{ column: "txs", label: "Calls", format: "compact", axis: "left", mark: "auto", transform: "none", dashed: false }], markers: [], bands: [], stacked: false, sortBy: "txs", sortDir: "desc", topN: 15, referenceLines: [], width: "full" }, { title: "Reverted calls", kind: "hbar", x: "method_id", series: [{ column: "reverted", label: "Reverted", format: "compact", axis: "left", mark: "auto", transform: "none", dashed: false }], markers: [], bands: [], stacked: false, sortBy: "txs", sortDir: "desc", topN: 15, referenceLines: [], width: "half" }, { title: "Callers per method", kind: "hbar", x: "method_id", series: [{ column: "callers", label: "Callers", format: "compact", axis: "left", mark: "auto", transform: "none", dashed: false }], markers: [], bands: [], stacked: false, sortBy: "txs", sortDir: "desc", topN: 15, referenceLines: [], width: "half" }], callouts: [] },
  },
  {
    q: "Top contracts by gas charged",
    title: "Top contracts by gas charged",
    note: "Gas charged is summed from transaction receipts. The top 15 contracts over the last 30 days; the explorer names contracts from their verified code.",
    sql: "SELECT lower(concat('0x', hex(`to`))) AS contract, sum(gas_used) AS gas_charged, count() AS txs, uniqExact(`from`) AS senders, round(100 * sum(gas_used) / sum(sum(gas_used)) OVER (), 2) AS share_pct, count() OVER () AS of_total FROM raw_txs WHERE chain_id = 43114 AND block_time >= toStartOfDay(now()) - INTERVAL 30 DAY AND `to` IS NOT NULL GROUP BY `to` ORDER BY gas_charged DESC LIMIT 15",
    chart: { kind: "bar", x: "contract", series: [{ column: "gas_charged", label: "Gas charged", unit: "gas" }] },
    drill: { sql: "SELECT block_time AS t, block_number, concat('0x', hex(hash)) AS tx_hash, lower(concat('0x', hex(`from`))) AS from_address, lower(concat('0x', hex(`to`))) AS to_address, concat('0x', hex(substring(input, 1, 4))) AS method_id, gas_used AS gas_charged, toFloat64(gas_used) * gas_price / 1e18 AS fee_avax, toUInt8(success) AS status FROM raw_txs WHERE chain_id = 43114 AND block_time >= toStartOfDay(now()) - INTERVAL 30 DAY AND `to` = {{contract:bytes}} ORDER BY block_time DESC LIMIT 50", title: "Transactions to {{contract}} in the last 30 days" },
    visual: { stats: [{ label: "Gas leader", column: "gas_charged", agg: "max", format: "gas" }, { label: "Leader's share", column: "share_pct", agg: "max", format: "percent" }, { label: "Top 15 share", column: "share_pct", agg: "sum", format: "percent" }, { label: "Most transactions", column: "txs", agg: "max", format: "compact" }], panels: [{ title: "Gas charged", kind: "hbar", x: "contract", series: [{ column: "gas_charged", label: "Gas charged", format: "gas", axis: "left", mark: "auto", transform: "none", dashed: false }], markers: [], bands: [], stacked: false, sortBy: "gas_charged", sortDir: "desc", topN: 15, referenceLines: [], width: "full" }, { title: "Transactions", kind: "hbar", x: "contract", series: [{ column: "txs", label: "Transactions", format: "compact", axis: "left", mark: "auto", transform: "none", dashed: false }], markers: [], bands: [], stacked: false, sortBy: "gas_charged", sortDir: "desc", topN: 15, referenceLines: [], width: "half" }, { title: "Senders", kind: "hbar", x: "contract", series: [{ column: "senders", label: "Senders", format: "number", axis: "left", mark: "auto", transform: "none", dashed: false }], markers: [], bands: [], stacked: false, sortBy: "gas_charged", sortDir: "desc", topN: 15, referenceLines: [], width: "half" }], callouts: [] },
  },
  {
    q: "USDC transfers per 5 minutes, count and volume",
    title: "USDC transfers per 5 minutes",
    note: "The transfers count all ERC-20 Transfer events on the USDC token contract. Volume is in USDC (6 decimals). The current 5-minute period is not yet complete.",
    sql: "SELECT toStartOfFiveMinutes(block_time) AS t, count() AS transfers, sum(toFloat64(reinterpretAsUInt256(reverse(substring(data, 1, 32))))) / 1e6 AS volume_usdc FROM raw_logs WHERE chain_id = 43114 AND block_time >= toStartOfFiveMinutes(now()) - INTERVAL 6 HOUR AND address = unhex('b97ef9ef8734c71904d8002f8b6bc66dd9c48a6e') AND topic0 = unhex('ddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef') GROUP BY t ORDER BY t WITH FILL STEP INTERVAL 5 MINUTE\nLIMIT 2000",
    chart: { kind: "line", x: "t", series: [{ column: "transfers", label: "Transfers", unit: "txs" }, { column: "volume_usdc", label: "Volume", unit: "USDC" }] },
    drill: { sql: "SELECT block_time AS t, block_number, concat('0x', hex(transaction_hash)) AS tx_hash, lower(concat('0x', hex(substring(topic1, 13, 20)))) AS from_address, lower(concat('0x', hex(substring(topic2, 13, 20)))) AS to_address, toFloat64(reinterpretAsUInt256(reverse(substring(data, 1, 32)))) / 1e6 AS amount_usdc FROM raw_logs WHERE chain_id = 43114 AND block_time >= toStartOfFiveMinutes(now()) - INTERVAL 6 HOUR AND toStartOfFiveMinutes(block_time) = {{t}} AND address = unhex('b97ef9ef8734c71904d8002f8b6bc66dd9c48a6e') AND topic0 = unhex('ddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef') ORDER BY block_time DESC LIMIT 50", title: "USDC transfers in the 5 minutes from {{t}}" },
    visual: { stats: [{ label: "Transfers", column: "transfers", agg: "sum", format: "compact" }, { label: "Volume", column: "volume_usdc", agg: "sum", format: "compact" }, { label: "Peak transfers", column: "transfers", agg: "max", format: "number" }, { label: "Peak volume", column: "volume_usdc", agg: "max", format: "compact" }], panels: [{ title: "Transfers and volume", kind: "bar", x: "t", series: [{ column: "transfers", label: "Transfers", format: "number", axis: "left", mark: "bar", transform: "none", dashed: false }, { column: "volume_usdc", label: "Volume (USDC)", format: "compact", axis: "right", mark: "line", transform: "none", dashed: false }], markers: [], bands: [], stacked: false, sortDir: "desc", referenceLines: [], width: "full" }, { title: "Cumulative volume", kind: "line", x: "t", series: [{ column: "volume_usdc", label: "Volume (USDC)", format: "compact", axis: "left", mark: "auto", transform: "cumulative", dashed: false }], markers: [], bands: [], stacked: false, sortDir: "desc", referenceLines: [], width: "full" }], callouts: [] },
  },
  {
    q: "Largest USDT transfers in the last hour",
    title: "Largest USDT transfers in the last hour",
    note: "USDT has 6 decimals. Token contract is 0x9702230a8ea53601f5cd2dc00fdbc13d4df4a8c7. Each row is one transfer.",
    sql: "SELECT block_time AS t, block_number, concat('0x', hex(transaction_hash)) AS tx_hash, lower(concat('0x', hex(substring(topic1, 13, 20)))) AS from_address, lower(concat('0x', hex(substring(topic2, 13, 20)))) AS to_address, toFloat64(reinterpretAsUInt256(reverse(substring(data, 1, 32)))) / 1e6 AS amount_usdt, lower(concat('0x', hex(tx_from))) AS tx_sender FROM raw_logs WHERE chain_id = 43114 AND block_time >= now() - INTERVAL 1 HOUR AND raw_logs.address = unhex('9702230a8ea53601f5cd2dc00fdbc13d4df4a8c7') AND topic0 = unhex('ddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef') ORDER BY amount_usdt DESC LIMIT 20",
    chart: { kind: "table", series: [] },
    drill: null,
    visual: { stats: [{ label: "Largest transfer", column: "amount_usdt", agg: "max", format: "compact" }, { label: "Transfers", column: "tx_hash", agg: "count", format: "number" }, { label: "Senders", column: "from_address", agg: "distinct", format: "number" }], panels: [{ title: "USDT flows", kind: "flow", x: "from_address", target: "to_address", series: [{ column: "amount_usdt", label: "USDT", format: "compact", axis: "left", mark: "auto", transform: "none", dashed: false }], markers: [], bands: [], stacked: false, sortDir: "desc", referenceLines: [], width: "full" }, { title: "Transfer sizes over time", kind: "bar", x: "t", series: [{ column: "amount_usdt", label: "USDT", format: "compact", axis: "left", mark: "bar", transform: "none", dashed: false }], markers: [], bands: [], stacked: false, sortDir: "desc", referenceLines: [], width: "full" }], callouts: [] },
  },
];

/** the P-Chain's suggestions (PCHAIN_EXAMPLES) */
const PCHAIN: Fixed[] = [
  {
    q: "AVAX staked on the Primary Network per day this month",
    title: "AVAX staked on the Primary Network this month",
    note: "Each day shows the stake from the most recent snapshot taken after 15 minutes past the hour. The current day's stake may change as the latest snapshot completes. Days with no snapshots stay empty.",
    sql: "WITH snaps AS (SELECT snapshot_time, sum(weight + delegator_weight) / 1e9 AS staked FROM p_validator_snapshots WHERE chain_id = 1 AND subnet_id = unhex(repeat('00', 32)) AND snapshot_time >= toStartOfMonth(now()) AND snapshot_time <= now() - INTERVAL 15 MINUTE GROUP BY snapshot_time) SELECT toDate(snapshot_time) AS t, toNullable(argMax(staked, snapshot_time)) AS staked_avax FROM snaps GROUP BY t ORDER BY t WITH FILL FROM toStartOfMonth(now()) TO toDate(now()) + INTERVAL 1 DAY STEP INTERVAL 1 DAY\nLIMIT 2000",
    chart: { kind: "line", x: "t", series: [{ column: "staked_avax", label: "AVAX staked", unit: "AVAX" }] },
    drill: null,
    visual: { stats: [{ label: "Staked", column: "staked_avax", agg: "last", format: "avax" }, { label: "Peak", column: "staked_avax", agg: "max", format: "avax" }, { label: "Low", column: "staked_avax", agg: "min", format: "avax" }, { label: "Month start", column: "staked_avax", agg: "first", format: "avax" }], panels: [{ title: "AVAX staked daily", kind: "line", x: "t", series: [{ column: "staked_avax", label: "Staked AVAX", format: "avax", axis: "left", mark: "auto", transform: "none", dashed: false }], markers: [], bands: [], stacked: false, sortDir: "desc", referenceLines: [], width: "full" }], callouts: [] },
  },
  {
    q: "Delegations per day, with AVAX delegated",
    title: "Delegations per day",
    note: "New delegations to Primary Network validators, with AVAX staked. The current day is not over.",
    sql: "SELECT toDate(block_time) AS t, countIf(tx_type IN ('AddPermissionlessDelegatorTx', 'AddDelegatorTx')) AS delegations, sumIf(ifNull(weight, 0), tx_type IN ('AddPermissionlessDelegatorTx', 'AddDelegatorTx')) / 1e9 AS delegated_avax FROM decoded_p_txs WHERE chain_id = 1 AND block_time >= toDate(now()) - INTERVAL 30 DAY GROUP BY t ORDER BY t WITH FILL FROM toDate(now()) - INTERVAL 30 DAY TO toDate(now()) + INTERVAL 1 DAY STEP INTERVAL 1 DAY\nLIMIT 2000",
    chart: { kind: "bar", x: "t", series: [{ column: "delegations", label: "Delegations", unit: "txs" }, { column: "delegated_avax", label: "AVAX delegated", unit: "AVAX" }] },
    drill: null,
    visual: { stats: [{ label: "Delegations", column: "delegations", agg: "sum", format: "compact" }, { label: "AVAX delegated", column: "delegated_avax", agg: "sum", format: "avax" }, { label: "Peak day", column: "delegations", agg: "max", format: "number" }, { label: "Peak AVAX day", column: "delegated_avax", agg: "max", format: "avax" }], panels: [{ title: "Delegations per day", kind: "bar", x: "t", series: [{ column: "delegations", label: "Delegations", format: "number", axis: "left", mark: "bar", transform: "none", dashed: false }], markers: [], bands: [], stacked: false, sortDir: "desc", referenceLines: [], width: "full" }, { title: "AVAX delegated per day", kind: "line", x: "t", series: [{ column: "delegated_avax", label: "AVAX delegated", format: "avax", axis: "left", mark: "line", transform: "none", dashed: false }], markers: [], bands: [], stacked: false, sortDir: "desc", referenceLines: [], width: "full" }], callouts: [] },
  },
  {
    q: "Largest validators right now, with delegators and uptime",
    title: "Largest validators now",
    note: "Top 20 validators on the Primary Network by stake. Uptime is the median of observations from its peers over the last hour.",
    sql: "WITH obs AS (\n  SELECT node_id, observer_node_id, avg(uptime_percent) AS u\n  FROM p_validator_observations\n  WHERE chain_id = 1 AND observed_at >= now() - INTERVAL 1 HOUR\n  GROUP BY node_id, observer_node_id\n), up AS (\n  SELECT node_id, quantileExact(0.5)(u) AS median_uptime, count() AS observers\n  FROM obs\n  GROUP BY node_id\n)\nSELECT\n  v.node_id AS node_id,\n  v.weight / 1e9 AS stake_avax,\n  v.delegator_weight / 1e9 AS delegated_avax,\n  v.delegator_count,\n  v.delegation_fee_percent AS fee_pct,\n  if(up.observers > 0, round(up.median_uptime, 2), NULL) AS uptime_pct,\n  up.observers,\n  count() OVER () AS of_total\nFROM p_validator_snapshots AS v\nLEFT JOIN up ON up.node_id = v.node_id\nWHERE v.chain_id = 1\n  AND v.subnet_id = unhex(repeat('00', 32))\n  AND v.snapshot_time = (\n    SELECT max(snapshot_time)\n    FROM p_validator_snapshots\n    WHERE chain_id = 1\n      AND snapshot_time <= now() - INTERVAL 15 MINUTE\n      AND snapshot_time >= now() - INTERVAL 1 DAY\n  )\nORDER BY v.weight DESC\nLIMIT 20",
    chart: { kind: "bar", x: "node_id", series: [{ column: "stake_avax", label: "Stake", unit: "AVAX" }, { column: "delegated_avax", label: "Delegated", unit: "AVAX" }] },
    drill: { sql: "SELECT block_time AS t, block_height, base58Encode(concat(tx_id, substring(SHA256(tx_id), 29, 4))) AS tx_id, tx_type, weight / 1e9 AS amount_avax, toString(end_time) AS ends FROM decoded_p_txs WHERE chain_id = 1 AND block_time >= now() - INTERVAL 365 DAY AND node_id = {{node_id:bytes}} ORDER BY block_time DESC LIMIT 50", title: "Transactions by {{node_id}}" },
    visual: { stats: [{ label: "Top 20 stake", column: "stake_avax", agg: "sum", format: "avax" }, { label: "Largest stake", column: "stake_avax", agg: "max", format: "avax" }, { label: "Delegators", column: "delegator_count", agg: "sum", format: "number" }, { label: "Uptime", column: "uptime_pct", agg: "avg", format: "percent" }], panels: [{ title: "Stake per validator", kind: "hbar", x: "node_id", series: [{ column: "stake_avax", label: "Stake", format: "avax", axis: "left", mark: "auto", transform: "none", dashed: false }, { column: "delegated_avax", label: "Delegated", format: "avax", axis: "left", mark: "auto", transform: "none", dashed: false }], markers: [], bands: [], stacked: false, sortBy: "stake_avax", sortDir: "desc", topN: 20, referenceLines: [], width: "full" }, { title: "Delegators", kind: "hbar", x: "node_id", series: [{ column: "delegator_count", label: "Delegators", format: "number", axis: "left", mark: "auto", transform: "none", dashed: false }], markers: [], bands: [], stacked: false, sortBy: "delegator_count", sortDir: "desc", topN: 10, referenceLines: [], width: "half" }, { title: "Uptime", kind: "hbar", x: "node_id", series: [{ column: "uptime_pct", label: "Uptime", format: "percent", axis: "left", mark: "auto", transform: "none", dashed: false }], markers: [], bands: [], stacked: false, sortBy: "uptime_pct", sortDir: "asc", topN: 10, referenceLines: [], width: "half" }], callouts: [] },
  },
  {
    q: "Validators whose staking period ends in the next 7 days",
    title: "Validators whose staking period ends in the next 7 days",
    note: "The Primary Network validators and L1 seats whose staking period or validation window ends between now and 7 days from now.",
    sql: "SELECT \n  base58Encode(concat(node_id, substring(SHA256(node_id), 29, 4))) AS node_id,\n  toString(end_time) AS ends,\n  weight / 1e9 AS stake_avax,\n  delegator_weight / 1e9 AS delegated_avax,\n  delegator_count,\n  delegation_fee_percent AS fee_pct\nFROM p_validator_snapshots \nWHERE chain_id = 1 \n  AND snapshot_time = (SELECT max(snapshot_time) FROM p_validator_snapshots WHERE chain_id = 1 AND snapshot_time <= now() - INTERVAL 15 MINUTE AND snapshot_time >= now() - INTERVAL 1 DAY)\n  AND end_time > now() \n  AND end_time <= now() + INTERVAL 7 DAY\nORDER BY end_time ASC\nLIMIT 2000",
    chart: { kind: "table", series: [] },
    drill: null,
    visual: { stats: [{ label: "Validators", column: "node_id", agg: "distinct", format: "number" }, { label: "Stake", column: "stake_avax", agg: "sum", format: "avax" }, { label: "Delegated", column: "delegated_avax", agg: "sum", format: "avax" }, { label: "Delegators", column: "delegator_count", agg: "sum", format: "number" }], panels: [{ title: "Largest stake ending", kind: "hbar", x: "node_id", series: [{ column: "stake_avax", label: "Stake", format: "avax", axis: "left", mark: "auto", transform: "none", dashed: false }], markers: [], bands: [], stacked: false, sortBy: "stake_avax", sortDir: "desc", topN: 15, referenceLines: [], width: "half" }, { title: "Most delegated ending", kind: "hbar", x: "node_id", series: [{ column: "delegated_avax", label: "Delegated", format: "avax", axis: "left", mark: "auto", transform: "none", dashed: false }], markers: [], bands: [], stacked: false, sortBy: "delegated_avax", sortDir: "desc", topN: 15, referenceLines: [], width: "half" }, { title: "Stake by end time", kind: "bar", x: "ends", series: [{ column: "stake_avax", label: "Stake", format: "avax", axis: "left", mark: "auto", transform: "none", dashed: false }, { column: "stake_avax", label: "Cumulative stake", format: "avax", axis: "right", mark: "line", transform: "cumulative", dashed: false }], markers: [], bands: [], stacked: false, sortDir: "desc", referenceLines: [], width: "full" }], callouts: [] },
  },
  {
    q: "L1s by active validators, with the balance left for fees",
    title: "L1s by active validators and fee balance",
    note: "Active L1 seats per L1, with the total balance remaining to pay continuous fees. The server names each L1.",
    sql: "SELECT base58Encode(concat(subnet_id, substring(SHA256(subnet_id), 29, 4))) AS subnet_id, count() AS validators, sum(balance) / 1e9 AS balance_avax FROM p_l1_validator_snapshots WHERE chain_id = 1 AND balance > 0 AND snapshot_time = (SELECT max(snapshot_time) FROM p_l1_validator_snapshots WHERE chain_id = 1 AND snapshot_time <= now() - INTERVAL 15 MINUTE AND snapshot_time >= now() - INTERVAL 1 DAY) GROUP BY subnet_id ORDER BY validators DESC\nLIMIT 2000",
    chart: { kind: "bar", x: "subnet_id", series: [{ column: "validators", label: "Active validators", unit: "count" }, { column: "balance_avax", label: "Balance for fees", unit: "AVAX" }] },
    drill: null,
    visual: { stats: [{ label: "Active validators", column: "validators", agg: "sum", format: "number" }, { label: "L1s", column: "subnet_id", agg: "distinct", format: "number" }, { label: "Fee balance", column: "balance_avax", agg: "sum", format: "avax" }, { label: "Largest set", column: "validators", agg: "max", format: "number" }], panels: [{ title: "Active validators", kind: "hbar", x: "subnet_id", series: [{ column: "validators", label: "Validators", format: "number", axis: "left", mark: "auto", transform: "none", dashed: false }], markers: [], bands: [], stacked: false, sortBy: "validators", sortDir: "desc", topN: 15, referenceLines: [], width: "half" }, { title: "Fee balance", kind: "hbar", x: "subnet_id", series: [{ column: "balance_avax", label: "Balance", format: "avax", axis: "left", mark: "auto", transform: "none", dashed: false }], markers: [], bands: [], stacked: false, sortBy: "balance_avax", sortDir: "desc", topN: 15, referenceLines: [], width: "half" }, { title: "Validators against balance", kind: "scatter", x: "validators", series: [{ column: "balance_avax", label: "Balance", format: "avax", axis: "left", mark: "auto", transform: "none", dashed: false }], markers: [], bands: [], stacked: false, sortDir: "desc", referenceLines: [], width: "full" }], callouts: [] },
  },
  {
    q: "L1 validator registrations per week",
    title: "L1 validator registrations per week",
    note: "The first validators of each new L1 are included. The current week is not over.",
    sql: "SELECT toMonday(block_time) AS t, sum(if(tx_type = 'ConvertSubnetToL1Tx', length(l1_validation_ids), 1)) AS registrations, countIf(tx_type = 'ConvertSubnetToL1Tx') AS conversions FROM decoded_p_txs WHERE chain_id = 1 AND tx_type IN ('ConvertSubnetToL1Tx', 'RegisterL1ValidatorTx') AND block_time >= toMonday(now()) - INTERVAL 12 WEEK GROUP BY t ORDER BY t WITH FILL FROM toMonday(now()) - INTERVAL 12 WEEK TO toMonday(now()) + INTERVAL 1 WEEK STEP INTERVAL 1 WEEK\nLIMIT 2000",
    chart: { kind: "bar", x: "t", series: [{ column: "registrations", label: "Registrations", unit: "validators" }, { column: "conversions", label: "New L1s", unit: "conversions" }] },
    drill: { sql: "SELECT block_time AS t, block_height, base58Encode(concat(tx_id, substring(SHA256(tx_id), 29, 4))) AS tx_id, tx_type, if(tx_type = 'ConvertSubnetToL1Tx', length(l1_validation_ids), 1) AS validators FROM decoded_p_txs WHERE chain_id = 1 AND tx_type IN ('ConvertSubnetToL1Tx', 'RegisterL1ValidatorTx') AND block_time >= toMonday(now()) - INTERVAL 12 WEEK AND toMonday(block_time) = {{t}} ORDER BY block_time DESC LIMIT 50", title: "L1 registrations in week of {{t}}" },
    visual: { stats: [{ label: "Registrations", column: "registrations", agg: "sum", format: "number" }, { label: "L1 conversions", column: "conversions", agg: "sum", format: "number" }, { label: "Peak week", column: "registrations", agg: "max", format: "number" }, { label: "Weekly average", column: "registrations", agg: "avg", format: "number" }], panels: [{ title: "Weekly registrations", kind: "bar", x: "t", series: [{ column: "registrations", label: "Registrations", format: "number", axis: "left", mark: "bar", transform: "none", dashed: false }, { column: "conversions", label: "L1 conversions", format: "number", axis: "left", mark: "line", transform: "none", dashed: false }], markers: [], bands: [], stacked: false, sortDir: "desc", referenceLines: [], width: "full" }], callouts: [] },
  },
  {
    q: "AVAX supply per day over the last 90 days",
    title: "P-Chain supply per day",
    note: "Shows the AVAX supply the P-Chain counts as issued after each day's last block, gross of what the C-Chain and X-Chain have burned. Some days may have no recorded blocks and are left empty.",
    sql: "SELECT toDate(block_time) AS t, toNullable(argMax(supply, block_height) / 1e9) AS pchain_supply_avax FROM p_exec_state_history WHERE chain_id = 1 AND block_time >= toDate(now()) - INTERVAL 90 DAY GROUP BY t ORDER BY t WITH FILL FROM toDate(now()) - INTERVAL 90 DAY TO toDate(now()) + INTERVAL 1 DAY STEP INTERVAL 1 DAY\nLIMIT 2000",
    chart: { kind: "line", x: "t", series: [{ column: "pchain_supply_avax", label: "P-Chain supply", unit: "AVAX" }] },
    drill: null,
    visual: { stats: [{ label: "Supply", column: "pchain_supply_avax", agg: "last", format: "avax" }, { label: "Starting supply", column: "pchain_supply_avax", agg: "first", format: "avax" }, { label: "Lowest", column: "pchain_supply_avax", agg: "min", format: "avax" }], panels: [{ title: "P-Chain supply", kind: "line", x: "t", series: [{ column: "pchain_supply_avax", label: "Supply (AVAX)", format: "avax", axis: "left", mark: "auto", transform: "none", dashed: false }], markers: [], bands: [], stacked: false, sortDir: "desc", referenceLines: [], width: "full" }], callouts: [] },
  },
  {
    q: "P-Chain transactions by type this week",
    title: "P-Chain transactions by type this week",
    note: "Transactions on the P-Chain since Monday. Each type groups its transactions; select one to see the detail.",
    sql: "SELECT tx_type, count() AS txs, round(100 * count() / sum(count()) OVER (), 2) AS share_pct FROM decoded_p_txs WHERE chain_id = 1 AND block_time >= toMonday(now()) GROUP BY tx_type ORDER BY txs DESC\nLIMIT 2000",
    chart: { kind: "bar", x: "tx_type", series: [{ column: "txs", label: "Transactions", unit: "txs" }, { column: "share_pct", label: "Share", unit: "%" }] },
    drill: { sql: "SELECT block_time AS t, block_height, base58Encode(concat(tx_id, substring(SHA256(tx_id), 29, 4))) AS tx_id, tx_type, if(node_id IS NULL, '', concat('NodeID-', base58Encode(concat(assumeNotNull(node_id), substring(SHA256(assumeNotNull(node_id)), 29, 4))))) AS node_id, weight / 1e9 AS amount_avax FROM decoded_p_txs WHERE chain_id = 1 AND block_time >= toMonday(now()) AND tx_type = {{tx_type}} ORDER BY block_time DESC LIMIT 50", title: "{{tx_type}} transactions this week" },
    visual: { stats: [{ label: "Transactions", column: "txs", agg: "sum", format: "number" }, { label: "Top type's share", column: "share_pct", agg: "max", format: "percent" }, { label: "Types", column: "tx_type", agg: "distinct", format: "number" }], panels: [{ title: "Transactions by type", kind: "hbar", x: "tx_type", series: [{ column: "txs", label: "Transactions", format: "number", axis: "left", mark: "auto", transform: "none", dashed: false }], markers: [], bands: [], stacked: false, sortBy: "txs", sortDir: "desc", topN: 13, referenceLines: [], width: "half" }, { title: "Share of transactions", kind: "hbar", x: "tx_type", series: [{ column: "share_pct", label: "Share", format: "percent", axis: "left", mark: "auto", transform: "none", dashed: false }], markers: [], bands: [], stacked: false, sortBy: "share_pct", sortDir: "desc", topN: 13, referenceLines: [], width: "half" }], callouts: [] },
  },
];

/* The L1s' suggestions (L1_EXAMPLES): one set for every mainnet L1, captured
   from Gunzilla (2026-09-28), with its chain id as {chain} and its drills'
   fee column as {fee}, which name the asked chain and its own token */
const L1: Fixed[] = [
  {
    q: "Daily transactions over the last 30 days, with reverts",
    title: "Daily transactions in the last 30 days",
    note: "Transactions per day with reverted ones and the revert rate, over the last 30 days. The current day is not over, so its last count is partial.",
    sql: "SELECT toDate(block_time) AS t, count() AS txs, countIf(NOT success) AS reverted, round(100 * countIf(NOT success) / count(), 2) AS revert_pct FROM raw_txs WHERE chain_id = {chain} AND block_time >= toStartOfDay(now()) - INTERVAL 30 DAY GROUP BY t ORDER BY t WITH FILL STEP 1\nLIMIT 2000",
    chart: { kind: "bar", x: "t", series: [{ column: "txs", label: "Transactions", unit: "txs" }, { column: "reverted", label: "Reverted", unit: "txs" }] },
    drill: { sql: "SELECT block_time AS t, block_number, concat('0x', hex(hash)) AS tx_hash, lower(concat('0x', hex(`from`))) AS from_address, lower(concat('0x', hex(`to`))) AS to_address, concat('0x', hex(substring(input, 1, 4))) AS method_id, gas_used AS gas_charged, toFloat64(gas_used) * gas_price / 1e18 AS {fee}, toUInt8(success) AS status FROM raw_txs WHERE chain_id = {chain} AND block_time >= toStartOfDay(now()) - INTERVAL 30 DAY AND toDate(block_time) = {{t}} ORDER BY block_time DESC LIMIT 50", title: "Transactions on {{t}}" },
    visual: { stats: [{ label: "Transactions", column: "txs", agg: "sum", format: "compact", sub: "31 days" }, { label: "Peak day", column: "txs", agg: "max", format: "compact", sub: "Sep 6" }, { label: "Reverted", column: "reverted", agg: "sum", format: "number", sub: "1,540 on Sep 28" }, { label: "Peak revert rate", column: "revert_pct", agg: "max", format: "percent", sub: "Sep 28, day filling" }], panels: [{ title: "Daily transactions", kind: "bar", x: "t", series: [{ column: "txs", label: "Transactions", format: "compact", axis: "left", mark: "bar", transform: "none", dashed: false }], markers: [{ x: "2026-09-06", label: "Peak 519.5k" }], bands: [], stacked: false, sortDir: "desc", referenceLines: [], width: "full" }, { title: "Reverted per day", kind: "bar", x: "t", series: [{ column: "reverted", label: "Reverted", format: "number", axis: "left", mark: "bar", transform: "none", dashed: false }], markers: [{ x: "2026-09-28", label: "1,540 reverted" }], bands: [], stacked: false, sortDir: "desc", referenceLines: [], width: "half" }, { title: "Revert rate", kind: "line", x: "t", series: [{ column: "revert_pct", label: "Revert rate", format: "percent", axis: "left", mark: "line", transform: "none", dashed: false }], markers: [], bands: [], stacked: false, sortDir: "desc", referenceLines: [], width: "half" }], callouts: [] },
  },
  {
    q: "Daily active addresses over the last 30 days",
    title: "Daily active addresses, last 30 days",
    note: "Active addresses are the senders and recipients of transactions, and the explorer's own charts count more roles, so their figure is higher. The current day is not over.",
    sql: "SELECT toDate(block_time) AS t, uniqExactArray([`from`, `to`]) AS active_addresses, uniqExact(`from`) AS senders, count() AS txs FROM raw_txs WHERE chain_id = {chain} AND block_time >= toStartOfDay(now()) - INTERVAL 30 DAY GROUP BY t ORDER BY t WITH FILL TO toDate(now()) + 1 STEP 1\nLIMIT 2000",
    chart: { kind: "line", x: "t", series: [{ column: "active_addresses", label: "Active addresses", unit: "addresses" }, { column: "senders", label: "Senders", unit: "addresses" }] },
    drill: { sql: "SELECT block_time AS t, block_number, concat('0x', hex(hash)) AS tx_hash, lower(concat('0x', hex(`from`))) AS from_address, lower(concat('0x', hex(`to`))) AS to_address, concat('0x', hex(substring(input, 1, 4))) AS method_id, gas_used AS gas_charged, toFloat64(gas_used) * gas_price / 1e18 AS {fee}, toUInt8(success) AS status FROM raw_txs WHERE chain_id = {chain} AND block_time >= toStartOfDay(now()) - INTERVAL 30 DAY AND toDate(block_time) = {{t}} ORDER BY block_time DESC LIMIT 50", title: "Transactions on {{t}}" },
    visual: { stats: [{ label: "Peak active addresses", column: "active_addresses", agg: "max", format: "number", sub: "Aug 31" }, { label: "Daily average", column: "active_addresses", agg: "avg", format: "number", sub: "active addresses per day" }, { label: "Low", column: "active_addresses", agg: "min", format: "number", sub: "Sep 24" }, { label: "Transactions", column: "txs", agg: "sum", format: "number", sub: "over 31 days" }], panels: [{ title: "Daily active addresses", kind: "line", x: "t", series: [{ column: "active_addresses", label: "Active addresses", format: "number", axis: "left", mark: "auto", transform: "none", dashed: false }, { column: "senders", label: "Senders", format: "number", axis: "left", mark: "auto", transform: "none", dashed: true }], markers: [{ x: "2026-08-31", label: "Peak 20.3k" }, { x: "2026-09-24", label: "Low 10.1k" }, { x: "2026-09-15", label: "-8.4k from prior day" }], bands: [], stacked: false, sortDir: "desc", referenceLines: [], width: "full" }, { title: "Daily transactions", kind: "bar", x: "t", series: [{ column: "txs", label: "Transactions", format: "compact", axis: "left", mark: "auto", transform: "none", dashed: false }], markers: [{ x: "2026-09-06", label: "Peak 519k" }], bands: [], stacked: false, sortDir: "desc", referenceLines: [], width: "full" }], callouts: [] },
  },
  {
    q: "Top contracts by calls this week",
    title: "Top contracts by calls this week",
    note: "Contracts ranked by transactions sent to them since Monday, top 15 only. The current week is not over.",
    sql: "SELECT lower(concat('0x', hex(`to`))) AS address, count() AS txs, countIf(NOT success) AS reverted, uniqExact(`from`) AS senders, round(100 * count() / sum(count()) OVER (), 2) AS share_pct, count() OVER () AS of_total FROM raw_txs WHERE chain_id = {chain} AND block_time >= toMonday(now()) AND `to` IS NOT NULL AND length(input) >= 4 GROUP BY `to` ORDER BY txs DESC LIMIT 15",
    chart: { kind: "bar", x: "address", series: [{ column: "txs", label: "Calls", unit: "txs" }, { column: "reverted", label: "Reverted", unit: "txs" }] },
    drill: { sql: "SELECT block_time AS t, block_number, concat('0x', hex(hash)) AS tx_hash, lower(concat('0x', hex(`from`))) AS from_address, lower(concat('0x', hex(`to`))) AS to_address, concat('0x', hex(substring(input, 1, 4))) AS method_id, gas_used AS gas_charged, toFloat64(gas_used) * gas_price / 1e18 AS {fee}, toUInt8(success) AS status FROM raw_txs WHERE chain_id = {chain} AND block_time >= toMonday(now()) AND `to` = {{address:bytes}} AND length(input) >= 4 ORDER BY block_time DESC LIMIT 50", title: "Transactions calling {{address}} this week" },
    visual: { stats: [{ label: "Transactions", column: "txs", agg: "sum", format: "compact", sub: "top 15 of 18 contracts" }, { label: "Leader share", column: "share_pct", agg: "max", format: "percent", sub: "0x7052…c145 leads" }, { label: "Reverted", column: "reverted", agg: "sum", format: "number", sub: "all at one contract" }, { label: "Most senders", column: "senders", agg: "max", format: "compact", sub: "at 0x1c69…270a" }], panels: [{ title: "Calls per contract", kind: "hbar", x: "address", series: [{ column: "txs", label: "Transactions", format: "compact", axis: "left", mark: "auto", transform: "none", dashed: false }], markers: [], bands: [], stacked: false, sortBy: "txs", sortDir: "desc", topN: 15, referenceLines: [], width: "full" }, { title: "Senders per contract", kind: "hbar", x: "address", series: [{ column: "senders", label: "Senders", format: "compact", axis: "left", mark: "auto", transform: "none", dashed: false }], markers: [], bands: [], stacked: false, sortBy: "txs", sortDir: "desc", topN: 15, referenceLines: [], width: "half" }, { title: "Reverted per contract", kind: "hbar", x: "address", series: [{ column: "reverted", label: "Reverted", format: "number", axis: "left", mark: "auto", transform: "none", dashed: false }], markers: [], bands: [], stacked: false, sortBy: "txs", sortDir: "desc", topN: 15, referenceLines: [], width: "half" }], callouts: [] },
  },
  {
    q: "New contracts deployed per day this month",
    title: "New contracts deployed per day this month",
    note: "Contract creations counted from creation calls in traces, since the start of the month. Days with no deployments are absent, and the current day is not over.",
    sql: "SELECT toDate(block_time) AS t, count() AS contracts_deployed, countIf(NOT tx_success) AS reverted, uniqExact(tx_from) AS deployers FROM raw_traces WHERE chain_id = {chain} AND block_time >= toStartOfMonth(now()) AND startsWith(call_type, 'C' || 'REATE') GROUP BY t ORDER BY t\nLIMIT 2000",
    chart: { kind: "bar", x: "t", series: [{ column: "contracts_deployed", label: "Contracts deployed", unit: "contracts" }, { column: "reverted", label: "Reverted", unit: "contracts" }] },
    drill: { sql: "SELECT block_time AS t, block_number, concat('0x', hex(tx_hash)) AS tx_hash, lower(concat('0x', hex(tx_from))) AS from_address, lower(concat('0x', hex(`to`))) AS to_address, toUInt8(tx_success) AS status FROM raw_traces WHERE chain_id = {chain} AND block_time >= toStartOfMonth(now()) AND startsWith(call_type, 'C' || 'REATE') AND toDate(block_time) = {{t}} ORDER BY block_time DESC LIMIT 50", title: "Contract deployments on {{t}}" },
    visual: { stats: [{ label: "Contracts deployed", column: "contracts_deployed", agg: "sum", format: "number", sub: "on Sep 2" }, { label: "Deployers", column: "deployers", agg: "max", format: "number", sub: "one address" }, { label: "Reverted", column: "reverted", agg: "sum", format: "number", sub: "no failed creations" }], panels: [{ title: "Contracts per day", kind: "bar", x: "t", series: [{ column: "contracts_deployed", label: "Contracts deployed", format: "number", axis: "left", mark: "bar", transform: "none", dashed: false }], markers: [{ x: "2026-09-02", label: "2 contracts" }], bands: [], stacked: false, sortDir: "desc", referenceLines: [], width: "full" }], callouts: [] },
  },
  {
    q: "Gas used per day over the last 30 days",
    title: "Gas used per day, last 30 days",
    note: "Total gas used by blocks each day over the last 30 days. The current day is not over, so its last figure is partial.",
    sql: "SELECT toDate(block_time) AS t, sum(gas_used) AS block_gas_used, count() AS blocks FROM raw_blocks WHERE chain_id = {chain} AND block_time >= toStartOfDay(now()) - INTERVAL 30 DAY GROUP BY t ORDER BY t WITH FILL STEP 1\nLIMIT 2000",
    chart: { kind: "bar", x: "t", series: [{ column: "block_gas_used", label: "Gas used", unit: "gas" }] },
    drill: { sql: "SELECT block_number, block_time AS t, gas_used AS block_gas_used, gas_limit FROM raw_blocks WHERE chain_id = {chain} AND block_time >= toStartOfDay(now()) - INTERVAL 30 DAY AND toDate(block_time) = {{t}} ORDER BY gas_used DESC LIMIT 50", title: "Busiest blocks on {{t}}" },
    visual: { stats: [{ label: "Gas used", column: "block_gas_used", agg: "sum", format: "gas", sub: "31 days" }, { label: "Daily average", column: "block_gas_used", agg: "avg", format: "gas", sub: "per day" }, { label: "Peak day", column: "block_gas_used", agg: "max", format: "gas", sub: "Sep 6" }, { label: "Blocks", column: "blocks", agg: "sum", format: "compact", sub: "avg 41.9k per day" }], panels: [{ title: "Gas used per day", kind: "line", x: "t", series: [{ column: "block_gas_used", label: "Gas used", format: "gas", axis: "left", mark: "line", transform: "none", dashed: false }, { column: "blocks", label: "Blocks", format: "compact", axis: "right", mark: "bar", transform: "none", dashed: false }], markers: [{ x: "2026-09-06", label: "Peak 84.6B gas" }, { x: "2026-09-24", label: "Low 44.3B gas" }], bands: [], stacked: false, sortDir: "desc", referenceLines: [], width: "full" }], callouts: [] },
  },
  {
    q: "Busiest hours of the day this week",
    title: "Busiest hours of the day this week",
    note: "Transactions grouped by hour of day (UTC) since Monday; the current hour is not over, so today's latest hour is partial.",
    sql: "SELECT toHour(block_time) AS hour_of_day, count() AS txs, countIf(NOT success) AS reverted, uniqExact(`from`) AS senders, round(100 * count() / sum(count()) OVER (), 2) AS share_pct FROM raw_txs WHERE chain_id = {chain} AND block_time >= toMonday(now()) GROUP BY hour_of_day ORDER BY txs DESC\nLIMIT 2000",
    chart: { kind: "bar", x: "hour_of_day", series: [{ column: "txs", label: "Transactions", unit: "txs" }, { column: "reverted", label: "Reverted", unit: "txs" }] },
    drill: { sql: "SELECT block_time AS t, block_number, concat('0x', hex(hash)) AS tx_hash, lower(concat('0x', hex(`from`))) AS from_address, lower(concat('0x', hex(`to`))) AS to_address, concat('0x', hex(substring(input, 1, 4))) AS method_id, gas_used AS gas_charged, toFloat64(gas_used) * gas_price / 1e18 AS {fee}, toUInt8(success) AS status FROM raw_txs WHERE chain_id = {chain} AND block_time >= toMonday(now()) AND toHour(block_time) = {{hour_of_day}} ORDER BY block_time DESC LIMIT 50", title: "Transactions in hour {{hour_of_day}} since Monday" },
    visual: { stats: [{ label: "Transactions", column: "txs", agg: "sum", format: "compact", sub: "since Monday" }, { label: "Peak hour", column: "txs", agg: "max", format: "compact", sub: "16:00 UTC" }, { label: "Reverted", column: "reverted", agg: "sum", format: "number", sub: "478 at 17:00" }, { label: "Top hour share", column: "share_pct", agg: "max", format: "percent", sub: "of transactions" }], panels: [{ title: "Transactions per hour", kind: "bar", x: "hour_of_day", series: [{ column: "txs", label: "Transactions", format: "compact", axis: "left", mark: "bar", transform: "none", dashed: false }, { column: "senders", label: "Senders", format: "compact", axis: "right", mark: "line", transform: "none", dashed: false }], markers: [{ x: 16, label: "Peak 44.4k" }, { x: 8, label: "Low 7.2k" }], bands: [{ from: 13, to: 17, label: "Busy window" }], stacked: false, sortBy: "hour_of_day", sortDir: "asc", referenceLines: [], width: "full" }, { title: "Reverts per hour", kind: "bar", x: "hour_of_day", series: [{ column: "reverted", label: "Reverted", format: "number", axis: "left", mark: "auto", transform: "none", dashed: false }], markers: [{ x: 17, label: "Peak 478" }], bands: [], stacked: false, sortBy: "hour_of_day", sortDir: "asc", referenceLines: [], width: "full" }], callouts: [] },
  },
  {
    q: "Token contracts by transfers this week",
    title: "Token contracts by transfers this week",
    note: "Transfer events since Monday, the top 15 token contracts by transfer count. ERC-20 and ERC-721 tokens share the event. The current week is not over.",
    sql: "SELECT lower(concat('0x', hex(raw_logs.address))) AS token, count() AS transfers, uniqExact(transaction_hash) AS txs, uniqExactIf(topic1, topic1 != unhex(repeat('00', 32))) AS senders, round(100 * count() / sum(count()) OVER (), 2) AS share_pct, count() OVER () AS of_total FROM raw_logs WHERE chain_id = {chain} AND block_time >= toMonday(now()) AND topic0 = unhex('ddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef') GROUP BY raw_logs.address ORDER BY transfers DESC LIMIT 15",
    chart: { kind: "bar", x: "token", series: [{ column: "transfers", label: "Transfers", unit: "transfers" }] },
    drill: { sql: "SELECT block_time AS t, block_number, concat('0x', hex(transaction_hash)) AS tx_hash, lower(concat('0x', hex(substring(topic1, 13, 20)))) AS from_address, lower(concat('0x', hex(substring(topic2, 13, 20)))) AS to_address, lower(concat('0x', hex(raw_logs.address))) AS token FROM raw_logs WHERE chain_id = {chain} AND block_time >= toMonday(now()) AND topic0 = unhex('ddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef') AND raw_logs.address = {{token:bytes}} ORDER BY block_time DESC LIMIT 50", title: "Transfers of {{token}} since Monday" },
    visual: { stats: [{ label: "Transfers", column: "transfers", agg: "sum", format: "compact", sub: "since Monday" }, { label: "Leader share", column: "share_pct", agg: "max", format: "percent", sub: "of token transfers" }, { label: "Token contracts", column: "token", agg: "distinct", format: "number", sub: "with transfers" }, { label: "Senders", column: "senders", agg: "max", format: "compact", sub: "on leading token" }], panels: [{ title: "Transfers per token", kind: "hbar", x: "token", series: [{ column: "transfers", label: "Transfers", format: "compact", axis: "left", mark: "auto", transform: "none", dashed: false }], markers: [], bands: [], stacked: false, sortBy: "transfers", sortDir: "desc", referenceLines: [], width: "half" }, { title: "Senders per token", kind: "hbar", x: "token", series: [{ column: "senders", label: "Senders", format: "compact", axis: "left", mark: "auto", transform: "none", dashed: false }], markers: [], bands: [], stacked: false, sortBy: "transfers", sortDir: "desc", referenceLines: [], width: "half" }], callouts: [] },
  },
  {
    q: "Busiest senders this week",
    title: "Busiest senders since Monday",
    note: "Top 15 sending accounts by transaction count since Monday, with reverted transactions and share of all transactions counted in that period. The current week is not over.",
    sql: "SELECT lower(concat('0x', hex(`from`))) AS address, count() AS txs, countIf(NOT success) AS reverted, uniqExact(`to`) AS recipients, round(100 * count() / sum(count()) OVER (), 2) AS share_pct, count() OVER () AS of_total FROM raw_txs WHERE chain_id = {chain} AND block_time >= toMonday(now()) GROUP BY `from` ORDER BY txs DESC LIMIT 15",
    chart: { kind: "bar", x: "address", series: [{ column: "txs", label: "Transactions", unit: "txs" }, { column: "reverted", label: "Reverted", unit: "txs" }] },
    drill: { sql: "SELECT block_time AS t, block_number, concat('0x', hex(hash)) AS tx_hash, lower(concat('0x', hex(`from`))) AS from_address, lower(concat('0x', hex(`to`))) AS to_address, concat('0x', hex(substring(input, 1, 4))) AS method_id, gas_used AS gas_charged, toFloat64(gas_used) * gas_price / 1e18 AS {fee}, toUInt8(success) AS status FROM raw_txs WHERE chain_id = {chain} AND block_time >= toMonday(now()) AND `from` = {{address:bytes}} ORDER BY block_time DESC LIMIT 50", title: "Transactions from {{address}} since Monday" },
    visual: { stats: [{ label: "Senders", column: "of_total", agg: "max", format: "compact", sub: "active since Monday" }, { label: "Transactions", column: "txs", agg: "sum", format: "compact", sub: "top 15 senders only" }, { label: "Share", column: "share_pct", agg: "sum", format: "percent", sub: "top 15, of all transactions" }, { label: "Reverted", column: "reverted", agg: "sum", format: "number", sub: "all from one sender" }], panels: [{ title: "Transactions per sender", kind: "hbar", x: "address", series: [{ column: "txs", label: "Transactions", format: "compact", axis: "left", mark: "auto", transform: "none", dashed: false }], markers: [], bands: [], stacked: false, sortBy: "txs", sortDir: "desc", topN: 15, referenceLines: [], width: "full" }, { title: "Share of transactions", kind: "hbar", x: "address", series: [{ column: "share_pct", label: "Share", format: "percent", axis: "left", mark: "auto", transform: "none", dashed: false }], markers: [], bands: [], stacked: false, sortBy: "share_pct", sortDir: "desc", topN: 15, referenceLines: [], width: "half" }, { title: "Reverted per sender", kind: "hbar", x: "address", series: [{ column: "reverted", label: "Reverted", format: "number", axis: "left", mark: "auto", transform: "none", dashed: false }], markers: [], bands: [], stacked: false, sortBy: "reverted", sortDir: "desc", topN: 15, referenceLines: [], width: "half" }], callouts: [] },
  },
];

/** a question as recipeKey reads it: case, spacing and a closing mark do not matter */
const norm = (q: string) => q.toLowerCase().replace(/\s+/g, " ").replace(/[?.!\s]+$/, "").trim();

const BY_CHAIN = new Map<number, Map<string, Fixed>>([
  [43114, new Map(CCHAIN.map((f) => [norm(f.q), f]))],
  [1, new Map(PCHAIN.map((f) => [norm(f.q), f]))],
]);
const BY_L1 = new Map(L1.map((f) => [norm(f.q), f]));

/* the chains the L1 set answers: each numeric chain id the catalog lists on mainnet and never on Fuji, but the
   C-Chain's. A Fuji L1's suggestions go to the model as they did */
const idsOn = (testnet: boolean) =>
  new Set((l1ChainsData as { chainId: string | number; isTestnet?: boolean }[]).filter((c) => (c.isTestnet === true) === testnet && /^\d+$/.test(String(c.chainId))).map((c) => Number(c.chainId)));
const FUJI_IDS = idsOn(true);
const MAINNET_L1S = new Set([...idsOn(false)].filter((id) => id !== 43114 && !FUJI_IDS.has(id)));

/** a drill's fee column, in the chain's own token: fee_gun on Gunzilla */
const feeColumn = (symbol: string) => `fee_${symbol.toLowerCase().replace(/[^a-z0-9]/g, "") || "native"}`;

/** a suggestion's fixed answer on mainnet, as a recipe; null for any other question or chain. An L1's is filled in
    with the asked chain's id and token */
export function fixedRecipe(chainId: number, prompt: string, symbol = ""): Recipe | null {
  const own = BY_CHAIN.get(chainId)?.get(norm(prompt));
  const f = own ?? (MAINNET_L1S.has(chainId) ? BY_L1.get(norm(prompt)) : undefined);
  if (!f) return null;
  const fill = (sql: string) => (own ? sql : sql.replaceAll("{chain}", String(chainId)).replaceAll("{fee}", feeColumn(symbol)));
  return { question: f.q, title: f.title, note: f.note, sql: fill(f.sql), chart: f.chart, drill: f.drill && { ...f.drill, sql: fill(f.drill.sql) }, visual: f.visual, writer: "fixed SQL", at: 0 };
}

/** the chain a suggestion's fixed answer belongs to, when it is the other one: a P-Chain suggestion asked of the C-Chain */
export function fixedRoute(chainId: number, prompt: string): "p-chain" | "c-chain" | null {
  if (chainId === 43114 && BY_CHAIN.get(1)!.has(norm(prompt))) return "p-chain";
  if (chainId === 1 && BY_CHAIN.get(43114)!.has(norm(prompt))) return "c-chain";
  return null;
}
