/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by: scripts/generate-event-signatures.mts
 * 
 * This file contains event and function signature mappings for decoding EVM logs and transaction input
 */

export interface SignatureInput {
  name: string;
  type: string;
  indexed?: boolean;
  components?: SignatureInput[];
}

export interface EventSignature {
  name: string;
  signature: string;
  topic: string;
  indexedCount: number;
  inputs: SignatureInput[];
}

export interface FunctionSignature {
  name: string;
  signature: string;
  selector: string;
  inputs: SignatureInput[];
}

/**
 * Map from topic hash to array of event signature variants.
 * Multiple variants exist when different contracts have the same event signature
 * but different indexed parameters (e.g., ERC20 vs ERC721 Transfer).
 */
export const EVENT_SIGNATURES: Record<string, EventSignature[]> = {
  "0x8be0079c531659141344cd1fd0a4f28419497f9722a3daafe3b4186f6b6457e0": [
    {
      "name": "OwnershipTransferred",
      "signature": "OwnershipTransferred(address,address)",
      "topic": "0x8be0079c531659141344cd1fd0a4f28419497f9722a3daafe3b4186f6b6457e0",
      "indexedCount": 2,
      "inputs": [
        {
          "name": "previousOwner",
          "type": "address",
          "indexed": true
        },
        {
          "name": "newOwner",
          "type": "address",
          "indexed": true
        }
      ]
    }
  ],
  "0x62e78cea01bee320cd4e420270b5ea74000d11b0c9f74754ebdbfc544b05a258": [
    {
      "name": "Paused",
      "signature": "Paused(address)",
      "topic": "0x62e78cea01bee320cd4e420270b5ea74000d11b0c9f74754ebdbfc544b05a258",
      "indexedCount": 0,
      "inputs": [
        {
          "name": "account",
          "type": "address",
          "indexed": false
        }
      ]
    }
  ],
  "0x5db9ee0a495bf2e6ff9c91a7834c1ba4fdd244a5e8aa4e537bd38aeae4b073aa": [
    {
      "name": "Unpaused",
      "signature": "Unpaused(address)",
      "topic": "0x5db9ee0a495bf2e6ff9c91a7834c1ba4fdd244a5e8aa4e537bd38aeae4b073aa",
      "indexedCount": 0,
      "inputs": [
        {
          "name": "account",
          "type": "address",
          "indexed": false
        }
      ]
    }
  ],
  "0xbd79b86ffe0ab8e8776151514217cd7cacd52c909f66475c3af44e129f0b00ff": [
    {
      "name": "RoleAdminChanged",
      "signature": "RoleAdminChanged(bytes32,bytes32,bytes32)",
      "topic": "0xbd79b86ffe0ab8e8776151514217cd7cacd52c909f66475c3af44e129f0b00ff",
      "indexedCount": 3,
      "inputs": [
        {
          "name": "role",
          "type": "bytes32",
          "indexed": true
        },
        {
          "name": "previousAdminRole",
          "type": "bytes32",
          "indexed": true
        },
        {
          "name": "newAdminRole",
          "type": "bytes32",
          "indexed": true
        }
      ]
    }
  ],
  "0x2f8788117e7eff1d82e926ec794901d17c78024a50270940304540a733656f0d": [
    {
      "name": "RoleGranted",
      "signature": "RoleGranted(bytes32,address,address)",
      "topic": "0x2f8788117e7eff1d82e926ec794901d17c78024a50270940304540a733656f0d",
      "indexedCount": 3,
      "inputs": [
        {
          "name": "role",
          "type": "bytes32",
          "indexed": true
        },
        {
          "name": "account",
          "type": "address",
          "indexed": true
        },
        {
          "name": "sender",
          "type": "address",
          "indexed": true
        }
      ]
    }
  ],
  "0xf6391f5c32d9c69d2a47ea670b442974b53935d1edc7fd64eb21e047a839171b": [
    {
      "name": "RoleRevoked",
      "signature": "RoleRevoked(bytes32,address,address)",
      "topic": "0xf6391f5c32d9c69d2a47ea670b442974b53935d1edc7fd64eb21e047a839171b",
      "indexedCount": 3,
      "inputs": [
        {
          "name": "role",
          "type": "bytes32",
          "indexed": true
        },
        {
          "name": "account",
          "type": "address",
          "indexed": true
        },
        {
          "name": "sender",
          "type": "address",
          "indexed": true
        }
      ]
    }
  ],
  "0xbc7cd75a20ee27fd9adebab32041f755214dbc6bffa90cc0225b39da2e5c2d3b": [
    {
      "name": "Upgraded",
      "signature": "Upgraded(address)",
      "topic": "0xbc7cd75a20ee27fd9adebab32041f755214dbc6bffa90cc0225b39da2e5c2d3b",
      "indexedCount": 1,
      "inputs": [
        {
          "name": "implementation",
          "type": "address",
          "indexed": true
        }
      ]
    }
  ],
  "0x1cf3b03a6cf19fa2baba4df148e9dcabedea7f8a5c07840e207e5c089be95d3e": [
    {
      "name": "BeaconUpgraded",
      "signature": "BeaconUpgraded(address)",
      "topic": "0x1cf3b03a6cf19fa2baba4df148e9dcabedea7f8a5c07840e207e5c089be95d3e",
      "indexedCount": 1,
      "inputs": [
        {
          "name": "beacon",
          "type": "address",
          "indexed": true
        }
      ]
    }
  ],
  "0x7f26b83ff96e1f2b6a682f133852f6798a09c465da95921460cefb3847402498": [
    {
      "name": "Initialized",
      "signature": "Initialized(uint8)",
      "topic": "0x7f26b83ff96e1f2b6a682f133852f6798a09c465da95921460cefb3847402498",
      "indexedCount": 0,
      "inputs": [
        {
          "name": "version",
          "type": "uint8",
          "indexed": false
        }
      ]
    }
  ],
  "0xc3d58168c5ae7397731d063d5bbf3d657854427343f4c083240f7aacaa2d0f62": [
    {
      "name": "TransferSingle",
      "signature": "TransferSingle(address,address,address,uint256,uint256)",
      "topic": "0xc3d58168c5ae7397731d063d5bbf3d657854427343f4c083240f7aacaa2d0f62",
      "indexedCount": 3,
      "inputs": [
        {
          "name": "operator",
          "type": "address",
          "indexed": true
        },
        {
          "name": "from",
          "type": "address",
          "indexed": true
        },
        {
          "name": "to",
          "type": "address",
          "indexed": true
        },
        {
          "name": "id",
          "type": "uint256",
          "indexed": false
        },
        {
          "name": "value",
          "type": "uint256",
          "indexed": false
        }
      ]
    }
  ],
  "0x4a39dc06d4c0dbc64b70af90fd698a233a518aa5d07e595d983b8c0526c8f7fb": [
    {
      "name": "TransferBatch",
      "signature": "TransferBatch(address,address,address,uint256[],uint256[])",
      "topic": "0x4a39dc06d4c0dbc64b70af90fd698a233a518aa5d07e595d983b8c0526c8f7fb",
      "indexedCount": 3,
      "inputs": [
        {
          "name": "operator",
          "type": "address",
          "indexed": true
        },
        {
          "name": "from",
          "type": "address",
          "indexed": true
        },
        {
          "name": "to",
          "type": "address",
          "indexed": true
        },
        {
          "name": "ids",
          "type": "uint256[]",
          "indexed": false
        },
        {
          "name": "values",
          "type": "uint256[]",
          "indexed": false
        }
      ]
    }
  ],
  "0x17307eab39ab6107e8899845ad3d59bd9653f200f220920489ca2b5937696c31": [
    {
      "name": "ApprovalForAll",
      "signature": "ApprovalForAll(address,address,bool)",
      "topic": "0x17307eab39ab6107e8899845ad3d59bd9653f200f220920489ca2b5937696c31",
      "indexedCount": 2,
      "inputs": [
        {
          "name": "account",
          "type": "address",
          "indexed": true
        },
        {
          "name": "operator",
          "type": "address",
          "indexed": true
        },
        {
          "name": "approved",
          "type": "bool",
          "indexed": false
        }
      ]
    }
  ],
  "0x6bb7ff708619ba0610cba295a58592e0451dee2622938c8755667688daf3529b": [
    {
      "name": "URI",
      "signature": "URI(string,uint256)",
      "topic": "0x6bb7ff708619ba0610cba295a58592e0451dee2622938c8755667688daf3529b",
      "indexedCount": 1,
      "inputs": [
        {
          "name": "value",
          "type": "string",
          "indexed": false
        },
        {
          "name": "id",
          "type": "uint256",
          "indexed": true
        }
      ]
    }
  ],
  "0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef": [
    {
      "name": "Transfer",
      "signature": "Transfer(address,address,uint256)",
      "topic": "0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef",
      "indexedCount": 2,
      "inputs": [
        {
          "name": "from",
          "type": "address",
          "indexed": true
        },
        {
          "name": "to",
          "type": "address",
          "indexed": true
        },
        {
          "name": "value",
          "type": "uint256",
          "indexed": false
        }
      ]
    },
    {
      "name": "Transfer",
      "signature": "Transfer(address,address,uint256)",
      "topic": "0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef",
      "indexedCount": 3,
      "inputs": [
        {
          "name": "from",
          "type": "address",
          "indexed": true
        },
        {
          "name": "to",
          "type": "address",
          "indexed": true
        },
        {
          "name": "tokenId",
          "type": "uint256",
          "indexed": true
        }
      ]
    }
  ],
  "0x8c5be1e5ebec7d5bd14f71427d1e84f3dd0314c0f7b2291e5b200ac8c7c3b925": [
    {
      "name": "Approval",
      "signature": "Approval(address,address,uint256)",
      "topic": "0x8c5be1e5ebec7d5bd14f71427d1e84f3dd0314c0f7b2291e5b200ac8c7c3b925",
      "indexedCount": 2,
      "inputs": [
        {
          "name": "owner",
          "type": "address",
          "indexed": true
        },
        {
          "name": "spender",
          "type": "address",
          "indexed": true
        },
        {
          "name": "value",
          "type": "uint256",
          "indexed": false
        }
      ]
    },
    {
      "name": "Approval",
      "signature": "Approval(address,address,uint256)",
      "topic": "0x8c5be1e5ebec7d5bd14f71427d1e84f3dd0314c0f7b2291e5b200ac8c7c3b925",
      "indexedCount": 3,
      "inputs": [
        {
          "name": "owner",
          "type": "address",
          "indexed": true
        },
        {
          "name": "approved",
          "type": "address",
          "indexed": true
        },
        {
          "name": "tokenId",
          "type": "uint256",
          "indexed": true
        }
      ]
    }
  ],
  "0xb9eaeae386d339f8115782f297a9e5f0e13fb587cd6b0d502f113cb8dd4d6cb0": [
    {
      "name": "CallFailed",
      "signature": "CallFailed(address,uint256)",
      "topic": "0xb9eaeae386d339f8115782f297a9e5f0e13fb587cd6b0d502f113cb8dd4d6cb0",
      "indexedCount": 1,
      "inputs": [
        {
          "name": "recipientContract",
          "type": "address",
          "indexed": true
        },
        {
          "name": "amount",
          "type": "uint256",
          "indexed": false
        }
      ]
    }
  ],
  "0x104deb555f67e63782bb817bc26c39050894645f9b9f29c4be8ae68d0e8b7ff4": [
    {
      "name": "CallSucceeded",
      "signature": "CallSucceeded(address,uint256)",
      "topic": "0x104deb555f67e63782bb817bc26c39050894645f9b9f29c4be8ae68d0e8b7ff4",
      "indexedCount": 1,
      "inputs": [
        {
          "name": "recipientContract",
          "type": "address",
          "indexed": true
        },
        {
          "name": "amount",
          "type": "uint256",
          "indexed": false
        }
      ]
    }
  ],
  "0x6769a5f9bfc8b6e0db839ab981cbf9239274ae72d2d035081a9157d43bd33cb6": [
    {
      "name": "CollateralAdded",
      "signature": "CollateralAdded(bytes32,address,uint256,uint256)",
      "topic": "0x6769a5f9bfc8b6e0db839ab981cbf9239274ae72d2d035081a9157d43bd33cb6",
      "indexedCount": 2,
      "inputs": [
        {
          "name": "remoteBlockchainID",
          "type": "bytes32",
          "indexed": true
        },
        {
          "name": "remoteTokenTransferrerAddress",
          "type": "address",
          "indexed": true
        },
        {
          "name": "amount",
          "type": "uint256",
          "indexed": false
        },
        {
          "name": "remaining",
          "type": "uint256",
          "indexed": false
        }
      ]
    }
  ],
  "0xc7f505b2f371ae2175ee4913f4499e1f2633a7b5936321eed1cdaeb6115181d2": [
    {
      "name": "Initialized",
      "signature": "Initialized(uint64)",
      "topic": "0xc7f505b2f371ae2175ee4913f4499e1f2633a7b5936321eed1cdaeb6115181d2",
      "indexedCount": 0,
      "inputs": [
        {
          "name": "version",
          "type": "uint64",
          "indexed": false
        }
      ]
    }
  ],
  "0xa9a7ef57e41f05b4c15480842f5f0c27edfcbb553fed281f7c4068452cc1c02d": [
    {
      "name": "MinTeleporterVersionUpdated",
      "signature": "MinTeleporterVersionUpdated(uint256,uint256)",
      "topic": "0xa9a7ef57e41f05b4c15480842f5f0c27edfcbb553fed281f7c4068452cc1c02d",
      "indexedCount": 2,
      "inputs": [
        {
          "name": "oldMinTeleporterVersion",
          "type": "uint256",
          "indexed": true
        },
        {
          "name": "newMinTeleporterVersion",
          "type": "uint256",
          "indexed": true
        }
      ]
    }
  ],
  "0xf229b02a51a4c8d5ef03a096ae0dd727d7b48b710d21b50ebebb560eef739b90": [
    {
      "name": "RemoteRegistered",
      "signature": "RemoteRegistered(bytes32,address,uint256,uint8)",
      "topic": "0xf229b02a51a4c8d5ef03a096ae0dd727d7b48b710d21b50ebebb560eef739b90",
      "indexedCount": 2,
      "inputs": [
        {
          "name": "remoteBlockchainID",
          "type": "bytes32",
          "indexed": true
        },
        {
          "name": "remoteTokenTransferrerAddress",
          "type": "address",
          "indexed": true
        },
        {
          "name": "initialCollateralNeeded",
          "type": "uint256",
          "indexed": false
        },
        {
          "name": "tokenDecimals",
          "type": "uint8",
          "indexed": false
        }
      ]
    }
  ],
  "0x933f93e57a222e6330362af8b376d0a8725b6901e9a2fb86d00f169702b28a4c": [
    {
      "name": "TeleporterAddressPaused",
      "signature": "TeleporterAddressPaused(address)",
      "topic": "0x933f93e57a222e6330362af8b376d0a8725b6901e9a2fb86d00f169702b28a4c",
      "indexedCount": 1,
      "inputs": [
        {
          "name": "teleporterAddress",
          "type": "address",
          "indexed": true
        }
      ]
    }
  ],
  "0x844e2f3154214672229235858fd029d1dfd543901c6d05931f0bc2480a2d72c3": [
    {
      "name": "TeleporterAddressUnpaused",
      "signature": "TeleporterAddressUnpaused(address)",
      "topic": "0x844e2f3154214672229235858fd029d1dfd543901c6d05931f0bc2480a2d72c3",
      "indexedCount": 1,
      "inputs": [
        {
          "name": "teleporterAddress",
          "type": "address",
          "indexed": true
        }
      ]
    }
  ],
  "0x42eff9005856e3c586b096d67211a566dc926052119fd7cc08023c70937ecb30": [
    {
      "name": "TokensAndCallRouted",
      "signature": "TokensAndCallRouted(bytes32,(bytes32,address,address,bytes,uint256,uint256,address,address,address,uint256,uint256),uint256)",
      "topic": "0x42eff9005856e3c586b096d67211a566dc926052119fd7cc08023c70937ecb30",
      "indexedCount": 1,
      "inputs": [
        {
          "name": "teleporterMessageID",
          "type": "bytes32",
          "indexed": true
        },
        {
          "name": "input",
          "type": "tuple",
          "indexed": false,
          "components": [
            {
              "name": "destinationBlockchainID",
              "type": "bytes32"
            },
            {
              "name": "destinationTokenTransferrerAddress",
              "type": "address"
            },
            {
              "name": "recipientContract",
              "type": "address"
            },
            {
              "name": "recipientPayload",
              "type": "bytes"
            },
            {
              "name": "requiredGasLimit",
              "type": "uint256"
            },
            {
              "name": "recipientGasLimit",
              "type": "uint256"
            },
            {
              "name": "multiHopFallback",
              "type": "address"
            },
            {
              "name": "fallbackRecipient",
              "type": "address"
            },
            {
              "name": "primaryFeeTokenAddress",
              "type": "address"
            },
            {
              "name": "primaryFee",
              "type": "uint256"
            },
            {
              "name": "secondaryFee",
              "type": "uint256"
            }
          ]
        },
        {
          "name": "amount",
          "type": "uint256",
          "indexed": false
        }
      ]
    }
  ],
  "0x5d76dff81bf773b908b050fa113d39f7d8135bb4175398f313ea19cd3a1a0b16": [
    {
      "name": "TokensAndCallSent",
      "signature": "TokensAndCallSent(bytes32,address,(bytes32,address,address,bytes,uint256,uint256,address,address,address,uint256,uint256),uint256)",
      "topic": "0x5d76dff81bf773b908b050fa113d39f7d8135bb4175398f313ea19cd3a1a0b16",
      "indexedCount": 2,
      "inputs": [
        {
          "name": "teleporterMessageID",
          "type": "bytes32",
          "indexed": true
        },
        {
          "name": "sender",
          "type": "address",
          "indexed": true
        },
        {
          "name": "input",
          "type": "tuple",
          "indexed": false,
          "components": [
            {
              "name": "destinationBlockchainID",
              "type": "bytes32"
            },
            {
              "name": "destinationTokenTransferrerAddress",
              "type": "address"
            },
            {
              "name": "recipientContract",
              "type": "address"
            },
            {
              "name": "recipientPayload",
              "type": "bytes"
            },
            {
              "name": "requiredGasLimit",
              "type": "uint256"
            },
            {
              "name": "recipientGasLimit",
              "type": "uint256"
            },
            {
              "name": "multiHopFallback",
              "type": "address"
            },
            {
              "name": "fallbackRecipient",
              "type": "address"
            },
            {
              "name": "primaryFeeTokenAddress",
              "type": "address"
            },
            {
              "name": "primaryFee",
              "type": "uint256"
            },
            {
              "name": "secondaryFee",
              "type": "uint256"
            }
          ]
        },
        {
          "name": "amount",
          "type": "uint256",
          "indexed": false
        }
      ]
    }
  ],
  "0x825080857c76cef4a1629c0705a7f8b4ef0282ddcafde0b6715c4fb34b68aaf0": [
    {
      "name": "TokensRouted",
      "signature": "TokensRouted(bytes32,(bytes32,address,address,address,uint256,uint256,uint256,address),uint256)",
      "topic": "0x825080857c76cef4a1629c0705a7f8b4ef0282ddcafde0b6715c4fb34b68aaf0",
      "indexedCount": 1,
      "inputs": [
        {
          "name": "teleporterMessageID",
          "type": "bytes32",
          "indexed": true
        },
        {
          "name": "input",
          "type": "tuple",
          "indexed": false,
          "components": [
            {
              "name": "destinationBlockchainID",
              "type": "bytes32"
            },
            {
              "name": "destinationTokenTransferrerAddress",
              "type": "address"
            },
            {
              "name": "recipient",
              "type": "address"
            },
            {
              "name": "primaryFeeTokenAddress",
              "type": "address"
            },
            {
              "name": "primaryFee",
              "type": "uint256"
            },
            {
              "name": "secondaryFee",
              "type": "uint256"
            },
            {
              "name": "requiredGasLimit",
              "type": "uint256"
            },
            {
              "name": "multiHopFallback",
              "type": "address"
            }
          ]
        },
        {
          "name": "amount",
          "type": "uint256",
          "indexed": false
        }
      ]
    }
  ],
  "0x93f19bf1ec58a15dc643b37e7e18a1c13e85e06cd11929e283154691ace9fb52": [
    {
      "name": "TokensSent",
      "signature": "TokensSent(bytes32,address,(bytes32,address,address,address,uint256,uint256,uint256,address),uint256)",
      "topic": "0x93f19bf1ec58a15dc643b37e7e18a1c13e85e06cd11929e283154691ace9fb52",
      "indexedCount": 2,
      "inputs": [
        {
          "name": "teleporterMessageID",
          "type": "bytes32",
          "indexed": true
        },
        {
          "name": "sender",
          "type": "address",
          "indexed": true
        },
        {
          "name": "input",
          "type": "tuple",
          "indexed": false,
          "components": [
            {
              "name": "destinationBlockchainID",
              "type": "bytes32"
            },
            {
              "name": "destinationTokenTransferrerAddress",
              "type": "address"
            },
            {
              "name": "recipient",
              "type": "address"
            },
            {
              "name": "primaryFeeTokenAddress",
              "type": "address"
            },
            {
              "name": "primaryFee",
              "type": "uint256"
            },
            {
              "name": "secondaryFee",
              "type": "uint256"
            },
            {
              "name": "requiredGasLimit",
              "type": "uint256"
            },
            {
              "name": "multiHopFallback",
              "type": "address"
            }
          ]
        },
        {
          "name": "amount",
          "type": "uint256",
          "indexed": false
        }
      ]
    }
  ],
  "0x6352c5382c4a4578e712449ca65e83cdb392d045dfcf1cad9615189db2da244b": [
    {
      "name": "TokensWithdrawn",
      "signature": "TokensWithdrawn(address,uint256)",
      "topic": "0x6352c5382c4a4578e712449ca65e83cdb392d045dfcf1cad9615189db2da244b",
      "indexedCount": 1,
      "inputs": [
        {
          "name": "recipient",
          "type": "address",
          "indexed": true
        },
        {
          "name": "amount",
          "type": "uint256",
          "indexed": false
        }
      ]
    }
  ],
  "0xe1fffcc4923d04b559f4d29a8bfc6cda04eb5b0d3c460751c2402c5c5cc9109c": [
    {
      "name": "Deposit",
      "signature": "Deposit(address,uint256)",
      "topic": "0xe1fffcc4923d04b559f4d29a8bfc6cda04eb5b0d3c460751c2402c5c5cc9109c",
      "indexedCount": 1,
      "inputs": [
        {
          "name": "sender",
          "type": "address",
          "indexed": true
        },
        {
          "name": "amount",
          "type": "uint256",
          "indexed": false
        }
      ]
    }
  ],
  "0x0832c643b65d6d3724ed14ac3a655fbc7cae54fb010918b2c2f70ef6b1bb94a5": [
    {
      "name": "ReportBurnedTxFees",
      "signature": "ReportBurnedTxFees(bytes32,uint256)",
      "topic": "0x0832c643b65d6d3724ed14ac3a655fbc7cae54fb010918b2c2f70ef6b1bb94a5",
      "indexedCount": 1,
      "inputs": [
        {
          "name": "teleporterMessageID",
          "type": "bytes32",
          "indexed": true
        },
        {
          "name": "feesBurned",
          "type": "uint256",
          "indexed": false
        }
      ]
    }
  ],
  "0x7fcf532c15f0a6db0bd6d0e038bea71d30d808c7d98cb3bf7268a95bf5081b65": [
    {
      "name": "Withdrawal",
      "signature": "Withdrawal(address,uint256)",
      "topic": "0x7fcf532c15f0a6db0bd6d0e038bea71d30d808c7d98cb3bf7268a95bf5081b65",
      "indexedCount": 1,
      "inputs": [
        {
          "name": "sender",
          "type": "address",
          "indexed": true
        },
        {
          "name": "amount",
          "type": "uint256",
          "indexed": false
        }
      ]
    }
  ],
  "0xc1bfd1f1208927dfbd414041dcb5256e6c9ad90dd61aec3249facbd34ff7b3e1": [
    {
      "name": "AddFeeAmount",
      "signature": "AddFeeAmount(bytes32,(address,uint256))",
      "topic": "0xc1bfd1f1208927dfbd414041dcb5256e6c9ad90dd61aec3249facbd34ff7b3e1",
      "indexedCount": 1,
      "inputs": [
        {
          "name": "messageID",
          "type": "bytes32",
          "indexed": true
        },
        {
          "name": "updatedFeeInfo",
          "type": "tuple",
          "indexed": false,
          "components": [
            {
              "name": "feeTokenAddress",
              "type": "address"
            },
            {
              "name": "amount",
              "type": "uint256"
            }
          ]
        }
      ]
    }
  ],
  "0x1eac640109dc937d2a9f42735a05f794b39a5e3759d681951d671aabbce4b104": [
    {
      "name": "BlockchainIDInitialized",
      "signature": "BlockchainIDInitialized(bytes32)",
      "topic": "0x1eac640109dc937d2a9f42735a05f794b39a5e3759d681951d671aabbce4b104",
      "indexedCount": 1,
      "inputs": [
        {
          "name": "blockchainID",
          "type": "bytes32",
          "indexed": true
        }
      ]
    }
  ],
  "0x34795cc6b122b9a0ae684946319f1e14a577b4e8f9b3dda9ac94c21a54d3188c": [
    {
      "name": "MessageExecuted",
      "signature": "MessageExecuted(bytes32,bytes32)",
      "topic": "0x34795cc6b122b9a0ae684946319f1e14a577b4e8f9b3dda9ac94c21a54d3188c",
      "indexedCount": 2,
      "inputs": [
        {
          "name": "messageID",
          "type": "bytes32",
          "indexed": true
        },
        {
          "name": "sourceBlockchainID",
          "type": "bytes32",
          "indexed": true
        }
      ]
    }
  ],
  "0x4619adc1017b82e02eaefac01a43d50d6d8de4460774bc370c3ff0210d40c985": [
    {
      "name": "MessageExecutionFailed",
      "signature": "MessageExecutionFailed(bytes32,bytes32,(uint256,address,bytes32,address,uint256,address[],(uint256,address)[],bytes))",
      "topic": "0x4619adc1017b82e02eaefac01a43d50d6d8de4460774bc370c3ff0210d40c985",
      "indexedCount": 2,
      "inputs": [
        {
          "name": "messageID",
          "type": "bytes32",
          "indexed": true
        },
        {
          "name": "sourceBlockchainID",
          "type": "bytes32",
          "indexed": true
        },
        {
          "name": "message",
          "type": "tuple",
          "indexed": false,
          "components": [
            {
              "name": "messageNonce",
              "type": "uint256"
            },
            {
              "name": "originSenderAddress",
              "type": "address"
            },
            {
              "name": "destinationBlockchainID",
              "type": "bytes32"
            },
            {
              "name": "destinationAddress",
              "type": "address"
            },
            {
              "name": "requiredGasLimit",
              "type": "uint256"
            },
            {
              "name": "allowedRelayerAddresses",
              "type": "address[]"
            },
            {
              "name": "receipts",
              "type": "tuple[]",
              "components": [
                {
                  "name": "receivedMessageNonce",
                  "type": "uint256"
                },
                {
                  "name": "relayerRewardAddress",
                  "type": "address"
                }
              ]
            },
            {
              "name": "message",
              "type": "bytes"
            }
          ]
        }
      ]
    }
  ],
  "0xd13a7935f29af029349bed0a2097455b91fd06190a30478c575db3f31e00bf57": [
    {
      "name": "ReceiptReceived",
      "signature": "ReceiptReceived(bytes32,bytes32,address,(address,uint256))",
      "topic": "0xd13a7935f29af029349bed0a2097455b91fd06190a30478c575db3f31e00bf57",
      "indexedCount": 3,
      "inputs": [
        {
          "name": "messageID",
          "type": "bytes32",
          "indexed": true
        },
        {
          "name": "destinationBlockchainID",
          "type": "bytes32",
          "indexed": true
        },
        {
          "name": "relayerRewardAddress",
          "type": "address",
          "indexed": true
        },
        {
          "name": "feeInfo",
          "type": "tuple",
          "indexed": false,
          "components": [
            {
              "name": "feeTokenAddress",
              "type": "address"
            },
            {
              "name": "amount",
              "type": "uint256"
            }
          ]
        }
      ]
    }
  ],
  "0x292ee90bbaf70b5d4936025e09d56ba08f3e421156b6a568cf3c2840d9343e34": [
    {
      "name": "ReceiveCrossChainMessage",
      "signature": "ReceiveCrossChainMessage(bytes32,bytes32,address,address,(uint256,address,bytes32,address,uint256,address[],(uint256,address)[],bytes))",
      "topic": "0x292ee90bbaf70b5d4936025e09d56ba08f3e421156b6a568cf3c2840d9343e34",
      "indexedCount": 3,
      "inputs": [
        {
          "name": "messageID",
          "type": "bytes32",
          "indexed": true
        },
        {
          "name": "sourceBlockchainID",
          "type": "bytes32",
          "indexed": true
        },
        {
          "name": "deliverer",
          "type": "address",
          "indexed": true
        },
        {
          "name": "rewardRedeemer",
          "type": "address",
          "indexed": false
        },
        {
          "name": "message",
          "type": "tuple",
          "indexed": false,
          "components": [
            {
              "name": "messageNonce",
              "type": "uint256"
            },
            {
              "name": "originSenderAddress",
              "type": "address"
            },
            {
              "name": "destinationBlockchainID",
              "type": "bytes32"
            },
            {
              "name": "destinationAddress",
              "type": "address"
            },
            {
              "name": "requiredGasLimit",
              "type": "uint256"
            },
            {
              "name": "allowedRelayerAddresses",
              "type": "address[]"
            },
            {
              "name": "receipts",
              "type": "tuple[]",
              "components": [
                {
                  "name": "receivedMessageNonce",
                  "type": "uint256"
                },
                {
                  "name": "relayerRewardAddress",
                  "type": "address"
                }
              ]
            },
            {
              "name": "message",
              "type": "bytes"
            }
          ]
        }
      ]
    }
  ],
  "0x3294c84e5b0f29d9803655319087207bc94f4db29f7927846944822773780b88": [
    {
      "name": "RelayerRewardsRedeemed",
      "signature": "RelayerRewardsRedeemed(address,address,uint256)",
      "topic": "0x3294c84e5b0f29d9803655319087207bc94f4db29f7927846944822773780b88",
      "indexedCount": 2,
      "inputs": [
        {
          "name": "redeemer",
          "type": "address",
          "indexed": true
        },
        {
          "name": "asset",
          "type": "address",
          "indexed": true
        },
        {
          "name": "amount",
          "type": "uint256",
          "indexed": false
        }
      ]
    }
  ],
  "0x2a211ad4a59ab9d003852404f9c57c690704ee755f3c79d2c2812ad32da99df8": [
    {
      "name": "SendCrossChainMessage",
      "signature": "SendCrossChainMessage(bytes32,bytes32,(uint256,address,bytes32,address,uint256,address[],(uint256,address)[],bytes),(address,uint256))",
      "topic": "0x2a211ad4a59ab9d003852404f9c57c690704ee755f3c79d2c2812ad32da99df8",
      "indexedCount": 2,
      "inputs": [
        {
          "name": "messageID",
          "type": "bytes32",
          "indexed": true
        },
        {
          "name": "destinationBlockchainID",
          "type": "bytes32",
          "indexed": true
        },
        {
          "name": "message",
          "type": "tuple",
          "indexed": false,
          "components": [
            {
              "name": "messageNonce",
              "type": "uint256"
            },
            {
              "name": "originSenderAddress",
              "type": "address"
            },
            {
              "name": "destinationBlockchainID",
              "type": "bytes32"
            },
            {
              "name": "destinationAddress",
              "type": "address"
            },
            {
              "name": "requiredGasLimit",
              "type": "uint256"
            },
            {
              "name": "allowedRelayerAddresses",
              "type": "address[]"
            },
            {
              "name": "receipts",
              "type": "tuple[]",
              "components": [
                {
                  "name": "receivedMessageNonce",
                  "type": "uint256"
                },
                {
                  "name": "relayerRewardAddress",
                  "type": "address"
                }
              ]
            },
            {
              "name": "message",
              "type": "bytes"
            }
          ]
        },
        {
          "name": "feeInfo",
          "type": "tuple",
          "indexed": false,
          "components": [
            {
              "name": "feeTokenAddress",
              "type": "address"
            },
            {
              "name": "amount",
              "type": "uint256"
            }
          ]
        }
      ]
    }
  ]
};

/**
 * Map from function selector to function signature.
 */
export const FUNCTION_SIGNATURES: Record<string, FunctionSignature> = {
  "0x4797735f": {
    "name": "ERC20_TOKEN_HOME_STORAGE_LOCATION",
    "signature": "ERC20_TOKEN_HOME_STORAGE_LOCATION()",
    "selector": "0x4797735f",
    "inputs": []
  },
  "0x909a6ac0": {
    "name": "TELEPORTER_REGISTRY_APP_STORAGE_LOCATION",
    "signature": "TELEPORTER_REGISTRY_APP_STORAGE_LOCATION()",
    "selector": "0x909a6ac0",
    "inputs": []
  },
  "0x62e3901b": {
    "name": "TOKEN_HOME_STORAGE_LOCATION",
    "signature": "TOKEN_HOME_STORAGE_LOCATION()",
    "selector": "0x62e3901b",
    "inputs": []
  },
  "0xfd658268": {
    "name": "addCollateral",
    "signature": "addCollateral(bytes32,address,uint256)",
    "selector": "0xfd658268",
    "inputs": [
      {
        "name": "remoteBlockchainID",
        "type": "bytes32"
      },
      {
        "name": "remoteTokenTransferrerAddress",
        "type": "address"
      },
      {
        "name": "amount",
        "type": "uint256"
      }
    ]
  },
  "0x4213cf78": {
    "name": "getBlockchainID",
    "signature": "getBlockchainID()",
    "selector": "0x4213cf78",
    "inputs": []
  },
  "0xd2cc7a70": {
    "name": "getMinTeleporterVersion",
    "signature": "getMinTeleporterVersion()",
    "selector": "0xd2cc7a70",
    "inputs": []
  },
  "0xc8511ada": {
    "name": "getRemoteTokenTransferrerSettings",
    "signature": "getRemoteTokenTransferrerSettings(bytes32,address)",
    "selector": "0xc8511ada",
    "inputs": [
      {
        "name": "remoteBlockchainID",
        "type": "bytes32"
      },
      {
        "name": "remoteTokenTransferrerAddress",
        "type": "address"
      }
    ]
  },
  "0x10fe9ae8": {
    "name": "getTokenAddress",
    "signature": "getTokenAddress()",
    "selector": "0x10fe9ae8",
    "inputs": []
  },
  "0x154d625a": {
    "name": "getTransferredBalance",
    "signature": "getTransferredBalance(bytes32,address)",
    "selector": "0x154d625a",
    "inputs": [
      {
        "name": "remoteBlockchainID",
        "type": "bytes32"
      },
      {
        "name": "remoteTokenTransferrerAddress",
        "type": "address"
      }
    ]
  },
  "0x3bb03890": {
    "name": "initialize",
    "signature": "initialize(address,address,uint256,address,uint8)",
    "selector": "0x3bb03890",
    "inputs": [
      {
        "name": "teleporterRegistryAddress",
        "type": "address"
      },
      {
        "name": "teleporterManager",
        "type": "address"
      },
      {
        "name": "minTeleporterVersion",
        "type": "uint256"
      },
      {
        "name": "tokenAddress",
        "type": "address"
      },
      {
        "name": "tokenDecimals",
        "type": "uint8"
      }
    ]
  },
  "0x97314297": {
    "name": "isTeleporterAddressPaused",
    "signature": "isTeleporterAddressPaused(address)",
    "selector": "0x97314297",
    "inputs": [
      {
        "name": "teleporterAddress",
        "type": "address"
      }
    ]
  },
  "0x8da5cb5b": {
    "name": "owner",
    "signature": "owner()",
    "selector": "0x8da5cb5b",
    "inputs": []
  },
  "0x2b0d8f18": {
    "name": "pauseTeleporterAddress",
    "signature": "pauseTeleporterAddress(address)",
    "selector": "0x2b0d8f18",
    "inputs": [
      {
        "name": "teleporterAddress",
        "type": "address"
      }
    ]
  },
  "0xc868efaa": {
    "name": "receiveTeleporterMessage",
    "signature": "receiveTeleporterMessage(bytes32,address,bytes)",
    "selector": "0xc868efaa",
    "inputs": [
      {
        "name": "sourceBlockchainID",
        "type": "bytes32"
      },
      {
        "name": "originSenderAddress",
        "type": "address"
      },
      {
        "name": "message",
        "type": "bytes"
      }
    ]
  },
  "0x715018a6": {
    "name": "renounceOwnership",
    "signature": "renounceOwnership()",
    "selector": "0x715018a6",
    "inputs": []
  },
  "0x5d16225d": {
    "name": "send",
    "signature": "send((bytes32,address,address,address,uint256,uint256,uint256,address),uint256)",
    "selector": "0x5d16225d",
    "inputs": [
      {
        "name": "input",
        "type": "tuple",
        "components": [
          {
            "name": "destinationBlockchainID",
            "type": "bytes32"
          },
          {
            "name": "destinationTokenTransferrerAddress",
            "type": "address"
          },
          {
            "name": "recipient",
            "type": "address"
          },
          {
            "name": "primaryFeeTokenAddress",
            "type": "address"
          },
          {
            "name": "primaryFee",
            "type": "uint256"
          },
          {
            "name": "secondaryFee",
            "type": "uint256"
          },
          {
            "name": "requiredGasLimit",
            "type": "uint256"
          },
          {
            "name": "multiHopFallback",
            "type": "address"
          }
        ]
      },
      {
        "name": "amount",
        "type": "uint256"
      }
    ]
  },
  "0x65690038": {
    "name": "sendAndCall",
    "signature": "sendAndCall((bytes32,address,address,bytes,uint256,uint256,address,address,address,uint256,uint256),uint256)",
    "selector": "0x65690038",
    "inputs": [
      {
        "name": "input",
        "type": "tuple",
        "components": [
          {
            "name": "destinationBlockchainID",
            "type": "bytes32"
          },
          {
            "name": "destinationTokenTransferrerAddress",
            "type": "address"
          },
          {
            "name": "recipientContract",
            "type": "address"
          },
          {
            "name": "recipientPayload",
            "type": "bytes"
          },
          {
            "name": "requiredGasLimit",
            "type": "uint256"
          },
          {
            "name": "recipientGasLimit",
            "type": "uint256"
          },
          {
            "name": "multiHopFallback",
            "type": "address"
          },
          {
            "name": "fallbackRecipient",
            "type": "address"
          },
          {
            "name": "primaryFeeTokenAddress",
            "type": "address"
          },
          {
            "name": "primaryFee",
            "type": "uint256"
          },
          {
            "name": "secondaryFee",
            "type": "uint256"
          }
        ]
      },
      {
        "name": "amount",
        "type": "uint256"
      }
    ]
  },
  "0xf2fde38b": {
    "name": "transferOwnership",
    "signature": "transferOwnership(address)",
    "selector": "0xf2fde38b",
    "inputs": [
      {
        "name": "newOwner",
        "type": "address"
      }
    ]
  },
  "0x4511243e": {
    "name": "unpauseTeleporterAddress",
    "signature": "unpauseTeleporterAddress(address)",
    "selector": "0x4511243e",
    "inputs": [
      {
        "name": "teleporterAddress",
        "type": "address"
      }
    ]
  },
  "0x5eb99514": {
    "name": "updateMinTeleporterVersion",
    "signature": "updateMinTeleporterVersion(uint256)",
    "selector": "0x5eb99514",
    "inputs": [
      {
        "name": "version",
        "type": "uint256"
      }
    ]
  },
  "0x62431a65": {
    "name": "ERC20_TOKEN_REMOTE_STORAGE_LOCATION",
    "signature": "ERC20_TOKEN_REMOTE_STORAGE_LOCATION()",
    "selector": "0x62431a65",
    "inputs": []
  },
  "0x15beb59f": {
    "name": "MULTI_HOP_CALL_GAS_PER_WORD",
    "signature": "MULTI_HOP_CALL_GAS_PER_WORD()",
    "selector": "0x15beb59f",
    "inputs": []
  },
  "0x71717c18": {
    "name": "MULTI_HOP_CALL_REQUIRED_GAS",
    "signature": "MULTI_HOP_CALL_REQUIRED_GAS()",
    "selector": "0x71717c18",
    "inputs": []
  },
  "0x5507f3d1": {
    "name": "MULTI_HOP_SEND_REQUIRED_GAS",
    "signature": "MULTI_HOP_SEND_REQUIRED_GAS()",
    "selector": "0x5507f3d1",
    "inputs": []
  },
  "0x254ac160": {
    "name": "REGISTER_REMOTE_REQUIRED_GAS",
    "signature": "REGISTER_REMOTE_REQUIRED_GAS()",
    "selector": "0x254ac160",
    "inputs": []
  },
  "0x35cac159": {
    "name": "TOKEN_REMOTE_STORAGE_LOCATION",
    "signature": "TOKEN_REMOTE_STORAGE_LOCATION()",
    "selector": "0x35cac159",
    "inputs": []
  },
  "0xdd62ed3e": {
    "name": "allowance",
    "signature": "allowance(address,address)",
    "selector": "0xdd62ed3e",
    "inputs": [
      {
        "name": "owner",
        "type": "address"
      },
      {
        "name": "spender",
        "type": "address"
      }
    ]
  },
  "0x095ea7b3": {
    "name": "approve",
    "signature": "approve(address,uint256)",
    "selector": "0x095ea7b3",
    "inputs": [
      {
        "name": "spender",
        "type": "address"
      },
      {
        "name": "value",
        "type": "uint256"
      }
    ]
  },
  "0x70a08231": {
    "name": "balanceOf",
    "signature": "balanceOf(address)",
    "selector": "0x70a08231",
    "inputs": [
      {
        "name": "account",
        "type": "address"
      }
    ]
  },
  "0xf3f981d8": {
    "name": "calculateNumWords",
    "signature": "calculateNumWords(uint256)",
    "selector": "0xf3f981d8",
    "inputs": [
      {
        "name": "payloadSize",
        "type": "uint256"
      }
    ]
  },
  "0x313ce567": {
    "name": "decimals",
    "signature": "decimals()",
    "selector": "0x313ce567",
    "inputs": []
  },
  "0xef793e2a": {
    "name": "getInitialReserveImbalance",
    "signature": "getInitialReserveImbalance()",
    "selector": "0xef793e2a",
    "inputs": []
  },
  "0x02a30c7d": {
    "name": "getIsCollateralized",
    "signature": "getIsCollateralized()",
    "selector": "0x02a30c7d",
    "inputs": []
  },
  "0x7ee3779a": {
    "name": "getMultiplyOnRemote",
    "signature": "getMultiplyOnRemote()",
    "selector": "0x7ee3779a",
    "inputs": []
  },
  "0xc3cd6927": {
    "name": "getTokenHomeAddress",
    "signature": "getTokenHomeAddress()",
    "selector": "0xc3cd6927",
    "inputs": []
  },
  "0xe0fd9cb8": {
    "name": "getTokenHomeBlockchainID",
    "signature": "getTokenHomeBlockchainID()",
    "selector": "0xe0fd9cb8",
    "inputs": []
  },
  "0x0733c8c8": {
    "name": "getTokenMultiplier",
    "signature": "getTokenMultiplier()",
    "selector": "0x0733c8c8",
    "inputs": []
  },
  "0xc9fe4ddf": {
    "name": "initialize",
    "signature": "initialize((address,address,uint256,bytes32,address,uint8),string,string,uint8)",
    "selector": "0xc9fe4ddf",
    "inputs": [
      {
        "name": "settings",
        "type": "tuple",
        "components": [
          {
            "name": "teleporterRegistryAddress",
            "type": "address"
          },
          {
            "name": "teleporterManager",
            "type": "address"
          },
          {
            "name": "minTeleporterVersion",
            "type": "uint256"
          },
          {
            "name": "tokenHomeBlockchainID",
            "type": "bytes32"
          },
          {
            "name": "tokenHomeAddress",
            "type": "address"
          },
          {
            "name": "tokenHomeDecimals",
            "type": "uint8"
          }
        ]
      },
      {
        "name": "tokenName",
        "type": "string"
      },
      {
        "name": "tokenSymbol",
        "type": "string"
      },
      {
        "name": "tokenDecimals",
        "type": "uint8"
      }
    ]
  },
  "0x06fdde03": {
    "name": "name",
    "signature": "name()",
    "selector": "0x06fdde03",
    "inputs": []
  },
  "0xb8a46d02": {
    "name": "registerWithHome",
    "signature": "registerWithHome((address,uint256))",
    "selector": "0xb8a46d02",
    "inputs": [
      {
        "name": "feeInfo",
        "type": "tuple",
        "components": [
          {
            "name": "feeTokenAddress",
            "type": "address"
          },
          {
            "name": "amount",
            "type": "uint256"
          }
        ]
      }
    ]
  },
  "0x95d89b41": {
    "name": "symbol",
    "signature": "symbol()",
    "selector": "0x95d89b41",
    "inputs": []
  },
  "0x18160ddd": {
    "name": "totalSupply",
    "signature": "totalSupply()",
    "selector": "0x18160ddd",
    "inputs": []
  },
  "0xa9059cbb": {
    "name": "transfer",
    "signature": "transfer(address,uint256)",
    "selector": "0xa9059cbb",
    "inputs": [
      {
        "name": "to",
        "type": "address"
      },
      {
        "name": "value",
        "type": "uint256"
      }
    ]
  },
  "0x23b872dd": {
    "name": "transferFrom",
    "signature": "transferFrom(address,address,uint256)",
    "selector": "0x23b872dd",
    "inputs": [
      {
        "name": "from",
        "type": "address"
      },
      {
        "name": "to",
        "type": "address"
      },
      {
        "name": "value",
        "type": "uint256"
      }
    ]
  },
  "0xefb5b95e": {
    "name": "NATIVE_TOKEN_HOME_STORAGE_LOCATION",
    "signature": "NATIVE_TOKEN_HOME_STORAGE_LOCATION()",
    "selector": "0xefb5b95e",
    "inputs": []
  },
  "0xb0b78b26": {
    "name": "addCollateral",
    "signature": "addCollateral(bytes32,address)",
    "selector": "0xb0b78b26",
    "inputs": [
      {
        "name": "remoteBlockchainID",
        "type": "bytes32"
      },
      {
        "name": "remoteTokenTransferrerAddress",
        "type": "address"
      }
    ]
  },
  "0xbe203094": {
    "name": "initialize",
    "signature": "initialize(address,address,uint256,address)",
    "selector": "0xbe203094",
    "inputs": [
      {
        "name": "teleporterRegistryAddress",
        "type": "address"
      },
      {
        "name": "teleporterManager",
        "type": "address"
      },
      {
        "name": "minTeleporterVersion",
        "type": "uint256"
      },
      {
        "name": "wrappedTokenAddress",
        "type": "address"
      }
    ]
  },
  "0x8bf2fa94": {
    "name": "send",
    "signature": "send((bytes32,address,address,address,uint256,uint256,uint256,address))",
    "selector": "0x8bf2fa94",
    "inputs": [
      {
        "name": "input",
        "type": "tuple",
        "components": [
          {
            "name": "destinationBlockchainID",
            "type": "bytes32"
          },
          {
            "name": "destinationTokenTransferrerAddress",
            "type": "address"
          },
          {
            "name": "recipient",
            "type": "address"
          },
          {
            "name": "primaryFeeTokenAddress",
            "type": "address"
          },
          {
            "name": "primaryFee",
            "type": "uint256"
          },
          {
            "name": "secondaryFee",
            "type": "uint256"
          },
          {
            "name": "requiredGasLimit",
            "type": "uint256"
          },
          {
            "name": "multiHopFallback",
            "type": "address"
          }
        ]
      }
    ]
  },
  "0x6e6eef8d": {
    "name": "sendAndCall",
    "signature": "sendAndCall((bytes32,address,address,bytes,uint256,uint256,address,address,address,uint256,uint256))",
    "selector": "0x6e6eef8d",
    "inputs": [
      {
        "name": "input",
        "type": "tuple",
        "components": [
          {
            "name": "destinationBlockchainID",
            "type": "bytes32"
          },
          {
            "name": "destinationTokenTransferrerAddress",
            "type": "address"
          },
          {
            "name": "recipientContract",
            "type": "address"
          },
          {
            "name": "recipientPayload",
            "type": "bytes"
          },
          {
            "name": "requiredGasLimit",
            "type": "uint256"
          },
          {
            "name": "recipientGasLimit",
            "type": "uint256"
          },
          {
            "name": "multiHopFallback",
            "type": "address"
          },
          {
            "name": "fallbackRecipient",
            "type": "address"
          },
          {
            "name": "primaryFeeTokenAddress",
            "type": "address"
          },
          {
            "name": "primaryFee",
            "type": "uint256"
          },
          {
            "name": "secondaryFee",
            "type": "uint256"
          }
        ]
      }
    ]
  },
  "0x347212c4": {
    "name": "BURNED_FOR_TRANSFER_ADDRESS",
    "signature": "BURNED_FOR_TRANSFER_ADDRESS()",
    "selector": "0x347212c4",
    "inputs": []
  },
  "0xc452165e": {
    "name": "BURNED_TX_FEES_ADDRESS",
    "signature": "BURNED_TX_FEES_ADDRESS()",
    "selector": "0xc452165e",
    "inputs": []
  },
  "0xed0ae4b0": {
    "name": "HOME_CHAIN_BURN_ADDRESS",
    "signature": "HOME_CHAIN_BURN_ADDRESS()",
    "selector": "0xed0ae4b0",
    "inputs": []
  },
  "0x329c3e12": {
    "name": "NATIVE_MINTER",
    "signature": "NATIVE_MINTER()",
    "selector": "0x329c3e12",
    "inputs": []
  },
  "0xa5717bc0": {
    "name": "NATIVE_TOKEN_REMOTE_STORAGE_LOCATION",
    "signature": "NATIVE_TOKEN_REMOTE_STORAGE_LOCATION()",
    "selector": "0xa5717bc0",
    "inputs": []
  },
  "0xd0e30db0": {
    "name": "deposit",
    "signature": "deposit()",
    "selector": "0xd0e30db0",
    "inputs": []
  },
  "0x0ca1c5c9": {
    "name": "getTotalMinted",
    "signature": "getTotalMinted()",
    "selector": "0x0ca1c5c9",
    "inputs": []
  },
  "0x8f6cec88": {
    "name": "initialize",
    "signature": "initialize((address,address,uint256,bytes32,address,uint8),string,uint256,uint256)",
    "selector": "0x8f6cec88",
    "inputs": [
      {
        "name": "settings",
        "type": "tuple",
        "components": [
          {
            "name": "teleporterRegistryAddress",
            "type": "address"
          },
          {
            "name": "teleporterManager",
            "type": "address"
          },
          {
            "name": "minTeleporterVersion",
            "type": "uint256"
          },
          {
            "name": "tokenHomeBlockchainID",
            "type": "bytes32"
          },
          {
            "name": "tokenHomeAddress",
            "type": "address"
          },
          {
            "name": "tokenHomeDecimals",
            "type": "uint8"
          }
        ]
      },
      {
        "name": "nativeAssetSymbol",
        "type": "string"
      },
      {
        "name": "initialReserveImbalance",
        "type": "uint256"
      },
      {
        "name": "burnedFeesReportingRewardPercentage",
        "type": "uint256"
      }
    ]
  },
  "0x55538c8b": {
    "name": "reportBurnedTxFees",
    "signature": "reportBurnedTxFees(uint256)",
    "selector": "0x55538c8b",
    "inputs": [
      {
        "name": "requiredGasLimit",
        "type": "uint256"
      }
    ]
  },
  "0x1906529c": {
    "name": "totalNativeAssetSupply",
    "signature": "totalNativeAssetSupply()",
    "selector": "0x1906529c",
    "inputs": []
  },
  "0x2e1a7d4d": {
    "name": "withdraw",
    "signature": "withdraw(uint256)",
    "selector": "0x2e1a7d4d",
    "inputs": [
      {
        "name": "amount",
        "type": "uint256"
      }
    ]
  },
  "0xb771b3bc": {
    "name": "WARP_MESSENGER",
    "signature": "WARP_MESSENGER()",
    "selector": "0xb771b3bc",
    "inputs": []
  },
  "0x8ac0fd04": {
    "name": "addFeeAmount",
    "signature": "addFeeAmount(bytes32,address,uint256)",
    "selector": "0x8ac0fd04",
    "inputs": [
      {
        "name": "messageID",
        "type": "bytes32"
      },
      {
        "name": "feeTokenAddress",
        "type": "address"
      },
      {
        "name": "additionalFeeAmount",
        "type": "uint256"
      }
    ]
  },
  "0xd127dc9b": {
    "name": "blockchainID",
    "signature": "blockchainID()",
    "selector": "0xd127dc9b",
    "inputs": []
  },
  "0xa8898181": {
    "name": "calculateMessageID",
    "signature": "calculateMessageID(bytes32,bytes32,uint256)",
    "selector": "0xa8898181",
    "inputs": [
      {
        "name": "sourceBlockchainID",
        "type": "bytes32"
      },
      {
        "name": "destinationBlockchainID",
        "type": "bytes32"
      },
      {
        "name": "nonce",
        "type": "uint256"
      }
    ]
  },
  "0xc473eef8": {
    "name": "checkRelayerRewardAmount",
    "signature": "checkRelayerRewardAmount(address,address)",
    "selector": "0xc473eef8",
    "inputs": [
      {
        "name": "relayer",
        "type": "address"
      },
      {
        "name": "feeAsset",
        "type": "address"
      }
    ]
  },
  "0xe69d606a": {
    "name": "getFeeInfo",
    "signature": "getFeeInfo(bytes32)",
    "selector": "0xe69d606a",
    "inputs": [
      {
        "name": "messageID",
        "type": "bytes32"
      }
    ]
  },
  "0x399b77da": {
    "name": "getMessageHash",
    "signature": "getMessageHash(bytes32)",
    "selector": "0x399b77da",
    "inputs": [
      {
        "name": "messageID",
        "type": "bytes32"
      }
    ]
  },
  "0xdf20e8bc": {
    "name": "getNextMessageID",
    "signature": "getNextMessageID(bytes32)",
    "selector": "0xdf20e8bc",
    "inputs": [
      {
        "name": "destinationBlockchainID",
        "type": "bytes32"
      }
    ]
  },
  "0x892bf412": {
    "name": "getReceiptAtIndex",
    "signature": "getReceiptAtIndex(bytes32,uint256)",
    "selector": "0x892bf412",
    "inputs": [
      {
        "name": "sourceBlockchainID",
        "type": "bytes32"
      },
      {
        "name": "index",
        "type": "uint256"
      }
    ]
  },
  "0x2bc8b0bf": {
    "name": "getReceiptQueueSize",
    "signature": "getReceiptQueueSize(bytes32)",
    "selector": "0x2bc8b0bf",
    "inputs": [
      {
        "name": "sourceBlockchainID",
        "type": "bytes32"
      }
    ]
  },
  "0x2e27c223": {
    "name": "getRelayerRewardAddress",
    "signature": "getRelayerRewardAddress(bytes32)",
    "selector": "0x2e27c223",
    "inputs": [
      {
        "name": "messageID",
        "type": "bytes32"
      }
    ]
  },
  "0x0af5b4ff": {
    "name": "initializeBlockchainID",
    "signature": "initializeBlockchainID()",
    "selector": "0x0af5b4ff",
    "inputs": []
  },
  "0xecc70428": {
    "name": "messageNonce",
    "signature": "messageNonce()",
    "selector": "0xecc70428",
    "inputs": []
  },
  "0xebc3b1ba": {
    "name": "messageReceived",
    "signature": "messageReceived(bytes32)",
    "selector": "0xebc3b1ba",
    "inputs": [
      {
        "name": "messageID",
        "type": "bytes32"
      }
    ]
  },
  "0xe6e67bd5": {
    "name": "receiptQueues",
    "signature": "receiptQueues(bytes32)",
    "selector": "0xe6e67bd5",
    "inputs": [
      {
        "name": "sourceBlockchainID",
        "type": "bytes32"
      }
    ]
  },
  "0xccb5f809": {
    "name": "receiveCrossChainMessage",
    "signature": "receiveCrossChainMessage(uint32,address)",
    "selector": "0xccb5f809",
    "inputs": [
      {
        "name": "messageIndex",
        "type": "uint32"
      },
      {
        "name": "relayerRewardAddress",
        "type": "address"
      }
    ]
  },
  "0x860a3b06": {
    "name": "receivedFailedMessageHashes",
    "signature": "receivedFailedMessageHashes(bytes32)",
    "selector": "0x860a3b06",
    "inputs": [
      {
        "name": "messageID",
        "type": "bytes32"
      }
    ]
  },
  "0x22296c3a": {
    "name": "redeemRelayerRewards",
    "signature": "redeemRelayerRewards(address)",
    "selector": "0x22296c3a",
    "inputs": [
      {
        "name": "feeAsset",
        "type": "address"
      }
    ]
  },
  "0xfc2d6197": {
    "name": "retryMessageExecution",
    "signature": "retryMessageExecution(bytes32,(uint256,address,bytes32,address,uint256,address[],(uint256,address)[],bytes))",
    "selector": "0xfc2d6197",
    "inputs": [
      {
        "name": "sourceBlockchainID",
        "type": "bytes32"
      },
      {
        "name": "message",
        "type": "tuple",
        "components": [
          {
            "name": "messageNonce",
            "type": "uint256"
          },
          {
            "name": "originSenderAddress",
            "type": "address"
          },
          {
            "name": "destinationBlockchainID",
            "type": "bytes32"
          },
          {
            "name": "destinationAddress",
            "type": "address"
          },
          {
            "name": "requiredGasLimit",
            "type": "uint256"
          },
          {
            "name": "allowedRelayerAddresses",
            "type": "address[]"
          },
          {
            "name": "receipts",
            "type": "tuple[]",
            "components": [
              {
                "name": "receivedMessageNonce",
                "type": "uint256"
              },
              {
                "name": "relayerRewardAddress",
                "type": "address"
              }
            ]
          },
          {
            "name": "message",
            "type": "bytes"
          }
        ]
      }
    ]
  },
  "0x8245a1b0": {
    "name": "retrySendCrossChainMessage",
    "signature": "retrySendCrossChainMessage((uint256,address,bytes32,address,uint256,address[],(uint256,address)[],bytes))",
    "selector": "0x8245a1b0",
    "inputs": [
      {
        "name": "message",
        "type": "tuple",
        "components": [
          {
            "name": "messageNonce",
            "type": "uint256"
          },
          {
            "name": "originSenderAddress",
            "type": "address"
          },
          {
            "name": "destinationBlockchainID",
            "type": "bytes32"
          },
          {
            "name": "destinationAddress",
            "type": "address"
          },
          {
            "name": "requiredGasLimit",
            "type": "uint256"
          },
          {
            "name": "allowedRelayerAddresses",
            "type": "address[]"
          },
          {
            "name": "receipts",
            "type": "tuple[]",
            "components": [
              {
                "name": "receivedMessageNonce",
                "type": "uint256"
              },
              {
                "name": "relayerRewardAddress",
                "type": "address"
              }
            ]
          },
          {
            "name": "message",
            "type": "bytes"
          }
        ]
      }
    ]
  },
  "0x62448850": {
    "name": "sendCrossChainMessage",
    "signature": "sendCrossChainMessage((bytes32,address,(address,uint256),uint256,address[],bytes))",
    "selector": "0x62448850",
    "inputs": [
      {
        "name": "messageInput",
        "type": "tuple",
        "components": [
          {
            "name": "destinationBlockchainID",
            "type": "bytes32"
          },
          {
            "name": "destinationAddress",
            "type": "address"
          },
          {
            "name": "feeInfo",
            "type": "tuple",
            "components": [
              {
                "name": "feeTokenAddress",
                "type": "address"
              },
              {
                "name": "amount",
                "type": "uint256"
              }
            ]
          },
          {
            "name": "requiredGasLimit",
            "type": "uint256"
          },
          {
            "name": "allowedRelayerAddresses",
            "type": "address[]"
          },
          {
            "name": "message",
            "type": "bytes"
          }
        ]
      }
    ]
  },
  "0xa9a85614": {
    "name": "sendSpecifiedReceipts",
    "signature": "sendSpecifiedReceipts(bytes32,bytes32[],(address,uint256),address[])",
    "selector": "0xa9a85614",
    "inputs": [
      {
        "name": "sourceBlockchainID",
        "type": "bytes32"
      },
      {
        "name": "messageIDs",
        "type": "bytes32[]"
      },
      {
        "name": "feeInfo",
        "type": "tuple",
        "components": [
          {
            "name": "feeTokenAddress",
            "type": "address"
          },
          {
            "name": "amount",
            "type": "uint256"
          }
        ]
      },
      {
        "name": "allowedRelayerAddresses",
        "type": "address[]"
      }
    ]
  },
  "0x2ca40f55": {
    "name": "sentMessageInfo",
    "signature": "sentMessageInfo(bytes32)",
    "selector": "0x2ca40f55",
    "inputs": [
      {
        "name": "messageID",
        "type": "bytes32"
      }
    ]
  }
};

/**
 * Get all event signature variants by topic hash
 */
export function getEventVariantsByTopic(topic: string): EventSignature[] | undefined {
  return EVENT_SIGNATURES[topic.toLowerCase()];
}

/**
 * Get the best matching event signature based on log structure.
 * Uses the number of indexed topics to determine the correct variant.
 */
export function getEventByTopic(topic: string, topicsCount: number): EventSignature | undefined {
  const variants = EVENT_SIGNATURES[topic.toLowerCase()];
  if (!variants || variants.length === 0) return undefined;
  
  // topicsCount includes topic[0] (event signature), so indexed params = topicsCount - 1
  const indexedParamsCount = topicsCount - 1;
  
  // Find variant matching the indexed count
  const exactMatch = variants.find(v => v.indexedCount === indexedParamsCount);
  if (exactMatch) return exactMatch;
  
  // Fallback to first variant if no exact match
  return variants[0];
}

/**
 * Get function signature by selector (first 4 bytes of input data)
 */
export function getFunctionBySelector(selector: string): FunctionSignature | undefined {
  return FUNCTION_SIGNATURES[selector.toLowerCase()];
}

/**
 * Format a decoded value for display based on its type
 */
function formatValue(value: string, type: string): string {
  if (type === 'address') {
    return '0x' + value.slice(-40);
  }
  if (type.startsWith('uint') || type.startsWith('int')) {
    try {
      return BigInt(value.startsWith('0x') ? value : '0x' + value).toString();
    } catch {
      return value;
    }
  }
  if (type === 'bool') {
    try {
      return BigInt(value.startsWith('0x') ? value : '0x' + value) !== BigInt(0) ? 'true' : 'false';
    } catch {
      return value;
    }
  }
  return value;
}

/**
 * Check if a type is dynamic (variable length)
 */
function isDynamicType(type: string, components?: SignatureInput[]): boolean {
  if (type === 'bytes' || type === 'string' || type.endsWith('[]')) {
    return true;
  }
  if (type === 'tuple' && components) {
    return components.some(c => isDynamicType(c.type, c.components));
  }
  return false;
}

/**
 * Decode tuple data from the data field
 * Handles both static and dynamic tuple encoding properly
 */
function decodeTupleData(
  data: string,
  offset: number,
  components: SignatureInput[]
): { values: Array<{ name: string; type: string; value: string }>; bytesConsumed: number } {
  const values: Array<{ name: string; type: string; value: string }> = [];
  
  // Check if this tuple contains any dynamic types
  const hasDynamicTypes = components.some(c => isDynamicType(c.type, c.components));
  
  if (!hasDynamicTypes) {
    // Simple case: all static types, elements are contiguous
    let currentOffset = offset;
    for (const component of components) {
      if (component.type === 'tuple' && component.components) {
        const result = decodeTupleData(data, currentOffset, component.components);
        values.push({
          name: component.name,
          type: component.type,
          value: JSON.stringify(result.values),
        });
        currentOffset += result.bytesConsumed;
      } else if (data.length >= currentOffset + 64) {
        const chunk = data.slice(currentOffset, currentOffset + 64);
        values.push({
          name: component.name,
          type: component.type,
          value: formatValue('0x' + chunk, component.type),
        });
        currentOffset += 64;
      }
    }
    return { values, bytesConsumed: currentOffset - offset };
  }
  
  // Complex case: tuple has dynamic types
  // Head contains: static values inline, dynamic values as offsets (relative to tuple start)
  // Tail contains: actual dynamic data
  
  const headSize = components.length * 64; // 32 bytes (64 hex chars) per slot in head
  let tailEnd = offset + headSize; // Track the end of tail for bytesConsumed
  let headOffset = offset;
  
  for (const component of components) {
    if (data.length < headOffset + 64) break;
    
    const chunk = data.slice(headOffset, headOffset + 64);
    
    if (component.type === 'tuple' && component.components) {
      // Nested tuple with dynamic types - follow offset
      if (isDynamicType(component.type, component.components)) {
        const tupleOffset = parseInt(chunk, 16) * 2; // Convert bytes to hex chars
        const tupleDataStart = offset + tupleOffset;
        const result = decodeTupleData(data, tupleDataStart, component.components);
        values.push({
          name: component.name,
          type: component.type,
          value: JSON.stringify(result.values),
        });
        tailEnd = Math.max(tailEnd, tupleDataStart + result.bytesConsumed);
      } else {
        // Static nested tuple - inline
        const result = decodeTupleData(data, headOffset, component.components);
        values.push({
          name: component.name,
          type: component.type,
          value: JSON.stringify(result.values),
        });
        // For static nested tuples, they take their actual size, not just one slot
        // But in ABI encoding, even nested tuples take slots in the head
      }
    } else if (component.type === 'bytes' || component.type === 'string') {
      // Dynamic type - chunk contains offset to actual data
      const dataOffset = parseInt(chunk, 16) * 2; // Convert bytes to hex chars
      const dataStart = offset + dataOffset;
      
      if (data.length >= dataStart + 64) {
        // Read length
        const lengthHex = data.slice(dataStart, dataStart + 64);
        const length = parseInt(lengthHex, 16);
        const dataEnd = dataStart + 64 + length * 2;
        
        if (component.type === 'string' && data.length >= dataEnd) {
          // Decode string
          const strHex = data.slice(dataStart + 64, dataEnd);
          try {
            const strBytes = strHex.match(/.{1,2}/g) || [];
            const str = strBytes.map(b => String.fromCharCode(parseInt(b, 16))).join('').replace(/\0/g, '');
            values.push({ name: component.name, type: component.type, value: str });
          } catch {
            values.push({ name: component.name, type: component.type, value: '[bytes]' });
          }
        } else {
          // Just show hex for bytes
          const bytesHex = data.slice(dataStart + 64, Math.min(dataEnd, dataStart + 64 + 128));
          values.push({
            name: component.name,
            type: component.type,
            value: length > 64 ? `0x${bytesHex}... (${length} bytes)` : `0x${bytesHex}`,
          });
        }
        tailEnd = Math.max(tailEnd, dataEnd);
      } else {
        values.push({ name: component.name, type: component.type, value: '[dynamic]' });
      }
    } else if (component.type.endsWith('[]')) {
      // Array - chunk contains offset
      const arrayOffset = parseInt(chunk, 16) * 2;
      const arrayStart = offset + arrayOffset;
      
      if (data.length >= arrayStart + 64) {
        const lengthHex = data.slice(arrayStart, arrayStart + 64);
        const length = parseInt(lengthHex, 16);
        values.push({
          name: component.name,
          type: component.type,
          value: `[array of ${length}]`,
        });
        // Estimate array end (rough - assumes 32 bytes per element)
        tailEnd = Math.max(tailEnd, arrayStart + 64 + length * 64);
      } else {
        values.push({ name: component.name, type: component.type, value: '[array]' });
      }
    } else {
      // Static type - value is inline in head
      values.push({
        name: component.name,
        type: component.type,
        value: formatValue('0x' + chunk, component.type),
      });
    }
    
    headOffset += 64;
  }
  
  return { values, bytesConsumed: tailEnd - offset };
}

/**
 * Decode event log using the signature map
 */
export function decodeEventLog(log: { topics: string[]; data: string }): {
  name: string;
  signature: string;
  params: Array<{ name: string; type: string; value: string; indexed: boolean; components?: Array<{ name: string; type: string; value: string }> }>;
} | null {
  if (!log.topics || log.topics.length === 0) return null;
  
  const eventSig = getEventByTopic(log.topics[0], log.topics.length);
  if (!eventSig) return null;
  
  const params: Array<{ name: string; type: string; value: string; indexed: boolean; components?: Array<{ name: string; type: string; value: string }> }> = [];
  
  let topicIndex = 1;
  let dataOffset = 0;
  const data = log.data.startsWith('0x') ? log.data.slice(2) : log.data;
  
  for (const input of eventSig.inputs) {
    let value = '';
    let decodedComponents: Array<{ name: string; type: string; value: string }> | undefined;
    
    if (input.indexed) {
      // Indexed parameters are in topics
      if (topicIndex < log.topics.length) {
        const topic = log.topics[topicIndex];
        value = formatValue(topic, input.type);
        topicIndex++;
      }
    } else {
      // Non-indexed parameters are in data
      if (input.type === 'tuple' && input.components) {
        // Decode tuple
        const result = decodeTupleData(data, dataOffset, input.components);
        decodedComponents = result.values;
        value = `(${result.values.map(v => v.value).join(', ')})`;
        dataOffset += result.bytesConsumed;
      } else if (data.length >= dataOffset + 64) {
        const chunk = data.slice(dataOffset, dataOffset + 64);
        value = formatValue('0x' + chunk, input.type);
        dataOffset += 64;
      }
    }
    
    const param: { name: string; type: string; value: string; indexed: boolean; components?: Array<{ name: string; type: string; value: string }> } = {
      name: input.name,
      type: input.type,
      value,
      indexed: input.indexed || false,
    };
    
    if (decodedComponents) {
      param.components = decodedComponents;
    }
    
    params.push(param);
  }
  
  return {
    name: eventSig.name,
    signature: eventSig.signature,
    params,
  };
}

/**
 * Decode transaction input data using the function signature map
 */
export function decodeFunctionInput(input: string): {
  name: string;
  signature: string;
  selector: string;
  params: Array<{ name: string; type: string; value: string; components?: Array<{ name: string; type: string; value: string }> }>;
} | null {
  if (!input || input === '0x' || input.length < 10) return null;
  
  const selector = input.slice(0, 10).toLowerCase();
  const funcSig = getFunctionBySelector(selector);
  if (!funcSig) return null;
  
  const params: Array<{ name: string; type: string; value: string; components?: Array<{ name: string; type: string; value: string }> }> = [];
  
  let dataOffset = 0;
  const data = input.slice(10); // Remove selector
  
  for (const inputDef of funcSig.inputs) {
    let value = '';
    let decodedComponents: Array<{ name: string; type: string; value: string }> | undefined;
    
    if (inputDef.type === 'tuple' && inputDef.components) {
      // Decode tuple
      const result = decodeTupleData(data, dataOffset, inputDef.components);
      decodedComponents = result.values;
      value = `(${result.values.map(v => v.value).join(', ')})`;
      dataOffset += result.bytesConsumed;
    } else if (inputDef.type.endsWith('[]')) {
      // Array type - read offset pointer for now
      if (data.length >= dataOffset + 64) {
        value = '[array]';
        dataOffset += 64;
      }
    } else if (inputDef.type === 'bytes' || inputDef.type === 'string') {
      // Dynamic type - read offset pointer
      if (data.length >= dataOffset + 64) {
        value = '[dynamic]';
        dataOffset += 64;
      }
    } else if (data.length >= dataOffset + 64) {
      const chunk = data.slice(dataOffset, dataOffset + 64);
      value = formatValue('0x' + chunk, inputDef.type);
      dataOffset += 64;
    }
    
    const param: { name: string; type: string; value: string; components?: Array<{ name: string; type: string; value: string }> } = {
      name: inputDef.name,
      type: inputDef.type,
      value,
    };
    
    if (decodedComponents) {
      param.components = decodedComponents;
    }
    
    params.push(param);
  }
  
  return {
    name: funcSig.name,
    signature: funcSig.signature,
    selector,
    params,
  };
}
